// Generated by stratus_hls 17.21-s100  (88813.070850)
// Sat Nov 16 23:15:37 2019
// from ../SobelFilter.cpp
#include "SobelFilter_rtl.h"

struct SobelFilter;
SobelFilter::SobelFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_rgb_busy("i_rgb_busy")
    ,i_rgb_vld("i_rgb_vld")
    ,i_rgb_data("i_rgb_data")
    ,o_newR_busy("o_newR_busy")
    ,o_newR_vld("o_newR_vld")
    ,o_newR_data("o_newR_data")
    ,o_newG_busy("o_newG_busy")
    ,o_newG_vld("o_newG_vld")
    ,o_newG_data("o_newG_data")
    ,o_newB_busy("o_newB_busy")
    ,o_newB_vld("o_newB_vld")
    ,o_newB_data("o_newB_data")
    ,o_newB_m_req_m_prev_trig_req("o_newB_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_4_7_out1("SobelFilter_Xor_1Ux1U_1U_4_7_out1")
    ,o_newB_m_unacked_req("o_newB_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_8_out1("SobelFilter_Or_1Ux1U_1U_4_8_out1")
    ,o_newG_m_req_m_prev_trig_req("o_newG_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_4_4_out1("SobelFilter_Xor_1Ux1U_1U_4_4_out1")
    ,o_newG_m_unacked_req("o_newG_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_5_out1("SobelFilter_Or_1Ux1U_1U_4_5_out1")
    ,o_newR_m_req_m_prev_trig_req("o_newR_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1Ux1U_1U_4_1_out1("SobelFilter_Xor_1Ux1U_1U_4_1_out1")
    ,o_newR_m_unacked_req("o_newR_m_unacked_req")
    ,SobelFilter_Or_1Ux1U_1U_4_2_out1("SobelFilter_Or_1Ux1U_1U_4_2_out1")
    ,SobelFilter_N_Muxb_1_2_4_4_10_out1("SobelFilter_N_Muxb_1_2_4_4_10_out1")
    ,SobelFilter_And_1Ux1U_1U_4_46_out1("SobelFilter_And_1Ux1U_1U_4_46_out1")
    ,SobelFilter_Not_1U_1U_4_45_out1("SobelFilter_Not_1U_1U_4_45_out1")
    ,SobelFilter_Or_1Ux1U_1U_4_43_out1("SobelFilter_Or_1Ux1U_1U_4_43_out1")
    ,i_rgb_m_unvalidated_req("i_rgb_m_unvalidated_req")
    ,SobelFilter_And_1Ux1U_1U_4_44_out1("SobelFilter_And_1Ux1U_1U_4_44_out1")
    ,global_state_next("global_state_next")
    ,SobelFilter_N_Mux_32_2_1_4_32_ctrl1("SobelFilter_N_Mux_32_2_1_4_32_ctrl1")
    ,SobelFilter_LessThan_32Sx9S_1U_4_31_in2("SobelFilter_LessThan_32Sx9S_1U_4_31_in2")
    ,gs_ctrl7("gs_ctrl7")
    ,SobelFilter_N_Mux_32_2_1_4_30_ctrl1("SobelFilter_N_Mux_32_2_1_4_30_ctrl1")
    ,SobelFilter_Add_32Sx16S_32S_4_23_in1("SobelFilter_Add_32Sx16S_32S_4_23_in1")
    ,SobelFilter_Mul_8Sx8U_16S_4_22_out1("SobelFilter_Mul_8Sx8U_16S_4_22_out1")
    ,SobelFilter_Mul_8Sx8U_16S_4_22_in1("SobelFilter_Mul_8Sx8U_16S_4_22_in1")
    ,SobelFilter_Add_32Sx16S_32S_4_21_in1("SobelFilter_Add_32Sx16S_32S_4_21_in1")
    ,gs_ctrl5("gs_ctrl5")
    ,SobelFilter_Add_32Sx16S_32S_4_21_in2("SobelFilter_Add_32Sx16S_32S_4_21_in2")
    ,gs_ctrl4("gs_ctrl4")
    ,SobelFilter_Mul_8Sx8U_16S_4_20_out1("SobelFilter_Mul_8Sx8U_16S_4_20_out1")
    ,SobelFilter_Mul_8Sx8U_16S_4_20_in1("SobelFilter_Mul_8Sx8U_16S_4_20_in1")
    ,SobelFilter_Mul_8Sx8U_16S_4_20_in2("SobelFilter_Mul_8Sx8U_16S_4_20_in2")
    ,gs_ctrl2("gs_ctrl2")
    ,SobelFilter_Add_5Sx2U_5S_4_18_out1("SobelFilter_Add_5Sx2U_5S_4_18_out1")
    ,SobelFilter_Add_5Sx2U_5S_4_18_in2("SobelFilter_Add_5Sx2U_5S_4_18_in2")
    ,SobelFilter_Mul_2Ux2U_4U_4_17_in2("SobelFilter_Mul_2Ux2U_4U_4_17_in2")
    ,SobelFilter_Add_2Ux2U_2U_4_16_in2("SobelFilter_Add_2Ux2U_2U_4_16_in2")
    ,gs_ctrl0("gs_ctrl0")
    ,SobelFilter_LessThan_32Sx9S_1U_4_31_out1("SobelFilter_LessThan_32Sx9S_1U_4_31_out1")
    ,SobelFilter_LessThan_2Ux2U_1U_4_26_out1("SobelFilter_LessThan_2Ux2U_1U_4_26_out1")
    ,s_reg_36("s_reg_36")
    ,SobelFilter_Add_2Ux2U_2U_4_19_out1("SobelFilter_Add_2Ux2U_2U_4_19_out1")
    ,s_reg_35("s_reg_35")
    ,s_reg_34("s_reg_34")
    ,SobelFilter_Add_32Sx16S_32S_4_23_out1("SobelFilter_Add_32Sx16S_32S_4_23_out1")
    ,s_reg_33("s_reg_33")
    ,SobelFilter_N_Mux_32_2_1_4_30_out1("SobelFilter_N_Mux_32_2_1_4_30_out1")
    ,SobelFilter_N_Mux_32_2_1_4_32_out1("SobelFilter_N_Mux_32_2_1_4_32_out1")
    ,SobelFilter_Add_32Sx16S_32S_4_21_out1("SobelFilter_Add_32Sx16S_32S_4_21_out1")
    ,s_reg_32("s_reg_32")
    ,SobelFilter_Add_2Ux2U_2U_4_16_out1("SobelFilter_Add_2Ux2U_2U_4_16_out1")
    ,s_reg_31("s_reg_31")
    ,s_reg_30("s_reg_30")
    ,SobelFilter_Not_1U_1U_4_47_out1("SobelFilter_Not_1U_1U_4_47_out1")
    ,SobelFilter_And_1Ux1U_1U_4_13_out1("SobelFilter_And_1Ux1U_1U_4_13_out1")
    ,SobelFilter_And_1Ux1U_1U_4_14_out1("SobelFilter_And_1Ux1U_1U_4_14_out1")
    ,SobelFilter_And_1Ux1U_1U_4_15_out1("SobelFilter_And_1Ux1U_1U_4_15_out1")
    ,SobelFilter_Not_1U_1U_4_9_out1("SobelFilter_Not_1U_1U_4_9_out1")
    ,o_newB_m_req_m_trig_req("o_newB_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1U_4_6_out1("SobelFilter_Not_1U_1U_4_6_out1")
    ,o_newG_m_req_m_trig_req("o_newG_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1U_4_3_out1("SobelFilter_Not_1U_1U_4_3_out1")
    ,o_newR_m_req_m_trig_req("o_newR_m_req_m_trig_req")
    ,i_rgb_m_busy_req_0("i_rgb_m_busy_req_0")
    ,SobelFilter_N_Mux_8_2_3_4_34_out1("SobelFilter_N_Mux_8_2_3_4_34_out1")
    ,SobelFilter_Mul_2Ux2U_4U_4_17_out1("SobelFilter_Mul_2Ux2U_4U_4_17_out1")
    ,SobelFilter_N_Mux_8_2_3_4_41_out1("SobelFilter_N_Mux_8_2_3_4_41_out1")
    ,SobelFilter_N_Mux_8_2_2_4_35_out1("SobelFilter_N_Mux_8_2_2_4_35_out1")
    ,s_reg_37("s_reg_37")
    ,SobelFilter_LessThan_2Ux2U_1U_4_27_out1("SobelFilter_LessThan_2Ux2U_1U_4_27_out1")
    ,SobelFilter_N_Mux_8_2_3_4_42_out1("SobelFilter_N_Mux_8_2_3_4_42_out1")
    ,SobelFilter_N_Mux_8_2_2_4_33_out1("SobelFilter_N_Mux_8_2_2_4_33_out1")
    ,global_state("global_state")
    ,stall0("stall0")
    ,SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_in1("SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_in1")
    ,SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1("SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1")
{
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1 = new 
  SobelFilter_ROM_9X8_embossFilterMask(
  "SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1");
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1->in1(
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_in1);
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1->out1(
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1);
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1->clk(i_clk);

  SC_METHOD(drive_o_newB_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newG_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newR_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newR_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newG_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newB_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_Not_1U_1U_4_47_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_13_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_14_out1 );
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_15_out1 );

  SC_METHOD(drive_s_reg_30);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_31);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_32);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_33);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_34);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_35);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_36);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_37);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_SobelFilter_Add_2Ux2U_2U_4_16_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_31 );

  SC_METHOD(SobelFilter_Add_2Ux2U_2U_4_16);
  sensitive << ( SobelFilter_Add_2Ux2U_2U_4_16_in2 );

  SC_METHOD(drive_SobelFilter_Mul_2Ux2U_4U_4_17_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_37 );
  sensitive << ( s_reg_35 );

  SC_METHOD(SobelFilter_Mul_2Ux2U_4U_4_17);
  sensitive << ( SobelFilter_Mul_2Ux2U_4U_4_17_in2 );

  SC_METHOD(drive_SobelFilter_Add_5Sx2U_5S_4_18_in2);
  sensitive << ( o_newR_data );

  SC_METHOD(SobelFilter_Add_5Sx2U_5S_4_18);
  sensitive << ( s_reg_30 );
  sensitive << ( SobelFilter_Add_5Sx2U_5S_4_18_in2 );

  SC_METHOD(SobelFilter_Add_2Ux2U_2U_4_19);
  sensitive << ( s_reg_35 );

  SC_METHOD(drive_SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_in1);
  sensitive << ( SobelFilter_Add_5Sx2U_5S_4_18_out1 );

  SC_METHOD(drive_SobelFilter_Mul_8Sx8U_16S_4_20_in2);
  sensitive << ( gs_ctrl2 );
  sensitive << ( o_newR_data );
  sensitive << ( SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1 );

  SC_METHOD(drive_SobelFilter_Mul_8Sx8U_16S_4_20_in1);
  sensitive << ( gs_ctrl2 );
  sensitive << ( s_reg_36 );

  SC_METHOD(SobelFilter_Mul_8Sx8U_16S_4_20);
  sensitive << ( SobelFilter_Mul_8Sx8U_16S_4_20_in1 );
  sensitive << ( SobelFilter_Mul_8Sx8U_16S_4_20_in2 );

  SC_METHOD(drive_SobelFilter_Add_32Sx16S_32S_4_21_in2);
  sensitive << ( gs_ctrl4 );
  sensitive << ( s_reg_34 );
  sensitive << ( s_reg_32 );

  SC_METHOD(drive_SobelFilter_Add_32Sx16S_32S_4_21_in1);
  sensitive << ( gs_ctrl5 );
  sensitive << ( SobelFilter_Mul_8Sx8U_16S_4_20_out1 );

  SC_METHOD(SobelFilter_Add_32Sx16S_32S_4_21);
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_21_in1 );
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_21_in2 );

  SC_METHOD(drive_SobelFilter_Mul_8Sx8U_16S_4_22_in1);
  sensitive << ( s_reg_36 );

  SC_METHOD(SobelFilter_Mul_8Sx8U_16S_4_22);
  sensitive << ( SobelFilter_Mul_8Sx8U_16S_4_22_in1 );
  sensitive << ( SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1 );

  SC_METHOD(drive_SobelFilter_Add_32Sx16S_32S_4_23_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( SobelFilter_Mul_8Sx8U_16S_4_22_out1 );

  SC_METHOD(SobelFilter_Add_32Sx16S_32S_4_23);
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_23_in1 );
  sensitive << ( s_reg_33 );

  SC_METHOD(SobelFilter_LessThan_2Ux2U_1U_4_26);
  sensitive << ( s_reg_35 );

  SC_METHOD(SobelFilter_LessThan_2Ux2U_1U_4_27);
  sensitive << ( s_reg_31 );

  SC_METHOD(drive_SobelFilter_N_Mux_32_2_1_4_30_ctrl1);
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_21_out1 );

  SC_METHOD(SobelFilter_N_Mux_32_2_1_4_30);
  sensitive << ( SobelFilter_N_Mux_32_2_1_4_30_ctrl1 );
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_21_out1 );

  SC_METHOD(drive_SobelFilter_LessThan_32Sx9S_1U_4_31_in2);
  sensitive << ( gs_ctrl7 );
  sensitive << ( s_reg_32 );
  sensitive << ( SobelFilter_N_Mux_32_2_1_4_30_out1 );

  SC_METHOD(SobelFilter_LessThan_32Sx9S_1U_4_31);
  sensitive << ( SobelFilter_LessThan_32Sx9S_1U_4_31_in2 );

  SC_METHOD(drive_SobelFilter_N_Mux_32_2_1_4_32_ctrl1);
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_23_out1 );

  SC_METHOD(SobelFilter_N_Mux_32_2_1_4_32);
  sensitive << ( SobelFilter_N_Mux_32_2_1_4_32_ctrl1 );
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_23_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_2_4_33);
  sensitive << ( SobelFilter_N_Mux_32_2_1_4_30_ctrl1 );
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_21_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_3_4_34);
  sensitive << ( SobelFilter_LessThan_32Sx9S_1U_4_31_out1 );
  sensitive << ( SobelFilter_N_Mux_8_2_2_4_33_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_2_4_35);
  sensitive << ( SobelFilter_N_Mux_32_2_1_4_32_ctrl1 );
  sensitive << ( SobelFilter_Add_32Sx16S_32S_4_23_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_3_4_41);
  sensitive << ( s_reg_37 );
  sensitive << ( o_newG_data );

  SC_METHOD(SobelFilter_N_Mux_8_2_3_4_42);
  sensitive << ( s_reg_37 );
  sensitive << ( o_newB_data );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( s_reg_37 );
  sensitive << ( SobelFilter_LessThan_2Ux2U_1U_4_27_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl2);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl4);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl5);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_gs_ctrl7);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_busy);
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_44_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_43);
  sensitive << ( i_rgb_vld );
  sensitive << ( i_rgb_m_unvalidated_req );

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_44);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_43_out1 );

  SC_METHOD(SobelFilter_Not_1U_1U_4_45);
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_44_out1 );

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_46);
  sensitive << ( i_rgb_vld );
  sensitive << ( SobelFilter_Not_1U_1U_4_45_out1 );

  SC_METHOD(SobelFilter_Not_1U_1U_4_47);
  sensitive << ( SobelFilter_And_1Ux1U_1U_4_46_out1 );

  SC_METHOD(drive_i_rgb_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_N_Muxb_1_2_4_4_10);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(drive_o_newR_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_2);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_4_1_out1 );
  sensitive << ( o_newR_m_unacked_req );

  SC_METHOD(drive_o_newR_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_13);
  sensitive << ( o_newR_vld );
  sensitive << ( o_newR_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_4_1);
  sensitive << ( o_newR_m_req_m_prev_trig_req );
  sensitive << ( o_newR_m_req_m_trig_req );

  SC_METHOD(drive_o_newR_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_4_3);
  sensitive << ( o_newR_m_req_m_trig_req );

  SC_METHOD(drive_o_newG_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_5_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_5);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_4_4_out1 );
  sensitive << ( o_newG_m_unacked_req );

  SC_METHOD(drive_o_newG_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_14);
  sensitive << ( o_newG_vld );
  sensitive << ( o_newG_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_4_4);
  sensitive << ( o_newG_m_req_m_prev_trig_req );
  sensitive << ( o_newG_m_req_m_trig_req );

  SC_METHOD(drive_o_newG_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_4_6);
  sensitive << ( o_newG_m_req_m_trig_req );

  SC_METHOD(drive_o_newB_vld);
  sensitive << ( SobelFilter_Or_1Ux1U_1U_4_8_out1 );

  SC_METHOD(SobelFilter_Or_1Ux1U_1U_4_8);
  sensitive << ( SobelFilter_Xor_1Ux1U_1U_4_7_out1 );
  sensitive << ( o_newB_m_unacked_req );

  SC_METHOD(drive_o_newB_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1Ux1U_1U_4_15);
  sensitive << ( o_newB_vld );
  sensitive << ( o_newB_busy );

  SC_METHOD(SobelFilter_Xor_1Ux1U_1U_4_7);
  sensitive << ( o_newB_m_req_m_prev_trig_req );
  sensitive << ( o_newB_m_req_m_trig_req );

  SC_METHOD(drive_o_newB_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1U_4_9);
  sensitive << ( o_newB_m_req_m_trig_req );

}
// resource: mux_8bx2i
// resource: regr_8b
void SobelFilter::drive_o_newB_data(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 5ULL: 
      o_newB_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_2_4_33_out1.read());
      break;
    case 7ULL: 
      o_newB_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_3_4_42_out1.read());
      break;
    }
  }
}
// resource: mux_8bx2i
// resource: regr_8b
void SobelFilter::drive_o_newG_data(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 4ULL: 
      if ( (!s_reg_37.read() && !SobelFilter_LessThan_2Ux2U_1U_4_27_out1.read())
       ) {
        o_newG_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_2_4_35_out1.read());
      } 
      break;
    case 6ULL: 
      o_newG_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_3_4_41_out1.read());
      break;
    }
  }
}
// resource: mux_8bx3i
// resource: regr_8b
void SobelFilter::drive_o_newR_data(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      o_newR_data = (sc_uint<8> ) (SobelFilter_Mul_2Ux2U_4U_4_17_out1.read());
      break;
    case 2ULL: 
      o_newR_data = SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1
                    .read();
      break;
    case 4ULL: 
      if ( s_reg_37.read() ) {
        o_newR_data = (sc_uint<8> ) (SobelFilter_Mul_2Ux2U_4U_4_17_out1.read());
      } else {
        if ( SobelFilter_LessThan_2Ux2U_1U_4_27_out1.read() ) {
          o_newR_data = (sc_uint<8> ) (SobelFilter_Mul_2Ux2U_4U_4_17_out1.read()
                        );
        } else {
          o_newR_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_3_4_34_out1.read())
          ;
        }
      }
      break;
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_i_rgb_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_busy_req_0 = 1ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 9ULL: 
        i_rgb_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: 
        i_rgb_m_busy_req_0 = 1ULL;
        break;
      case 4ULL: 
        if ( s_reg_37.read() ) {
          i_rgb_m_busy_req_0 = 0ULL;
        } else {
          if ( SobelFilter_LessThan_2Ux2U_1U_4_27_out1.read() ) {
            i_rgb_m_busy_req_0 = 0ULL;
          } 
        }
        break;
      }
    }
  }
}
// resource: regr_1b
void SobelFilter::drive_o_newR_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newR_m_req_m_trig_req = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 5ULL: 
        o_newR_m_req_m_trig_req = (sc_uint<1> ) (SobelFilter_Not_1U_1U_4_3_out1
                                  .read());
        break;
      }
    }
  }
}
// resource: regr_1b
void SobelFilter::drive_o_newG_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newG_m_req_m_trig_req = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 6ULL: 
        o_newG_m_req_m_trig_req = (sc_uint<1> ) (SobelFilter_Not_1U_1U_4_6_out1
                                  .read());
        break;
      }
    }
  }
}
// resource: regr_1b
void SobelFilter::drive_o_newB_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newB_m_req_m_trig_req = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 7ULL: 
        o_newB_m_req_m_trig_req = (sc_uint<1> ) (SobelFilter_Not_1U_1U_4_9_out1
                                  .read());
        break;
      }
    }
  }
}
// resource: mux_1bx5i
void SobelFilter::drive_stall0(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: 
    stall0 = SobelFilter_Not_1U_1U_4_47_out1.read();
    break;
  case 6ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_13_out1.read();
    break;
  case 7ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_14_out1.read();
    break;
  case 8ULL: 
    stall0 = SobelFilter_And_1Ux1U_1U_4_15_out1.read();
    break;
  }
}
// resource: mux_2bx2i
// resource: regr_2b
void SobelFilter::drive_s_reg_30(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_30 = 0ULL;
      break;
    case 4ULL: 
      if ( s_reg_37.read() );
      else {
        s_reg_30 = s_reg_31.read();
      }
      break;
    }
  }
}
// resource: regr_2b
void SobelFilter::drive_s_reg_31(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_31 = (sc_uint<2> ) (SobelFilter_Add_2Ux2U_2U_4_16_out1.read());
      break;
    case 4ULL: 
      if ( s_reg_37.read() );
      else {
        s_reg_31 = (sc_uint<2> ) (SobelFilter_Add_2Ux2U_2U_4_16_out1.read());
      }
      break;
    }
  }
}
// resource: mux_32bx4i
// resource: regr_32b
void SobelFilter::drive_s_reg_32(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_32 = 0ULL;
      break;
    case 2ULL: 
      s_reg_32 = (sc_uint<32> ) (SobelFilter_Add_32Sx16S_32S_4_21_out1.read());
      break;
    case 4ULL: 
      if ( s_reg_37.read() );
      else {
        if ( SobelFilter_LessThan_2Ux2U_1U_4_27_out1.read() );
        else {
          s_reg_32 = (sc_uint<32> ) (SobelFilter_N_Mux_32_2_1_4_32_out1.read());
        }
      }
      break;
    case 5ULL: 
      s_reg_32 = (sc_uint<32> ) (SobelFilter_N_Mux_32_2_1_4_30_out1.read());
      break;
    }
  }
}
// resource: mux_32bx2i
// resource: regr_32b
void SobelFilter::drive_s_reg_33(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_33 = 0ULL;
      break;
    case 2ULL: 
      s_reg_33 = (sc_uint<32> ) (SobelFilter_Add_32Sx16S_32S_4_23_out1.read());
      break;
    }
  }
}
// resource: mux_32bx2i
// resource: regr_32b
void SobelFilter::drive_s_reg_34(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_34 = 0ULL;
      break;
    case 3ULL: 
      s_reg_34 = (sc_uint<32> ) (SobelFilter_Add_32Sx16S_32S_4_21_out1.read());
      break;
    }
  }
}
// resource: mux_2bx2i
// resource: regr_2b
void SobelFilter::drive_s_reg_35(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 9ULL: 
      s_reg_35 = 0ULL;
      break;
    case 1ULL: 
      s_reg_35 = (sc_uint<2> ) (SobelFilter_Add_2Ux2U_2U_4_19_out1.read());
      break;
    case 4ULL: 
      if ( s_reg_37.read() );
      else {
        s_reg_35 = 0ULL;
      }
      break;
    }
  }
}
// resource: regr_24b
void SobelFilter::drive_s_reg_36(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 1ULL: 
      s_reg_36 = i_rgb_data.read();
      break;
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_s_reg_37(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 3ULL: 
      s_reg_37 = SobelFilter_LessThan_2Ux2U_1U_4_26_out1.read();
      break;
    case 5ULL: case 6ULL: 
      s_reg_37 = SobelFilter_LessThan_32Sx9S_1U_4_31_out1.read();
      break;
    }
  }
}
// resource: mux_2bx2i
void SobelFilter::drive_SobelFilter_Add_2Ux2U_2U_4_16_in2(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add_2Ux2U_2U_4_16_in2 = (sc_uint<2> ) (s_reg_31.read());
  } else {
    SobelFilter_Add_2Ux2U_2U_4_16_in2 = 0ULL;
  }
}
// resource: SobelFilter_Add_2Ux2U_2U_4  instance: SobelFilter_Add_2Ux2U_2U_4_16
void SobelFilter::SobelFilter_Add_2Ux2U_2U_4_16(){
  SobelFilter_Add_2Ux2U_2U_4_16_out1 = (/*cliff*/sc_uint<32>)(
                                       SobelFilter_Add_2Ux2U_2U_4_16_in2.read()
                                        + 1ULL);
}
// resource: mux_2bx2i
void SobelFilter::drive_SobelFilter_Mul_2Ux2U_4U_4_17_in2(){
  if ( gs_ctrl0.read() ) {
    if ( s_reg_37.read() ) {
      SobelFilter_Mul_2Ux2U_4U_4_17_in2 = s_reg_35.read();
    } else {
      SobelFilter_Mul_2Ux2U_4U_4_17_in2 = 0ULL;
    }
  } else {
    SobelFilter_Mul_2Ux2U_4U_4_17_in2 = 0ULL;
  }
}
// resource: SobelFilter_Mul_2Ux2U_4U_4  instance: SobelFilter_Mul_2Ux2U_4U_4_17
void SobelFilter::SobelFilter_Mul_2Ux2U_4U_4_17(){
  SobelFilter_Mul_2Ux2U_4U_4_17_out1 = SobelFilter_Mul_2Ux2U_4U_4_17_in2.read()
                                        * 3ULL;
}
void SobelFilter::drive_SobelFilter_Add_5Sx2U_5S_4_18_in2(){
  SobelFilter_Add_5Sx2U_5S_4_18_in2 = (sc_int<5> )((sc_uint<4> )o_newR_data
                                      .read());
}
// resource: SobelFilter_Add_5Sx2U_5S_4  instance: SobelFilter_Add_5Sx2U_5S_4_18
void SobelFilter::SobelFilter_Add_5Sx2U_5S_4_18(){
  SobelFilter_Add_5Sx2U_5S_4_18_out1 = (SobelFilter_Add_5Sx2U_5S_4_18_in2.read()
                                        + s_reg_30.read());
}
// resource: SobelFilter_Add_2Ux2U_2U_4  instance: SobelFilter_Add_2Ux2U_2U_4_19
void SobelFilter::SobelFilter_Add_2Ux2U_2U_4_19(){
  SobelFilter_Add_2Ux2U_2U_4_19_out1 = (/*cliff*/sc_uint<32>)((sc_uint<2> )
                                       s_reg_35.read() + 1ULL);
}
void SobelFilter::drive_SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_in1(){
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_in1 = (sc_uint<4> )SobelFilter_Add_5Sx2U_5S_4_18_out1
                                                                .read();
}
// resource: mux_8bx2i
void SobelFilter::drive_SobelFilter_Mul_8Sx8U_16S_4_20_in2(){
  if ( gs_ctrl2.read() ) {
    SobelFilter_Mul_8Sx8U_16S_4_20_in2 = (sc_int<8> ) (o_newR_data.read());
  } else {
    SobelFilter_Mul_8Sx8U_16S_4_20_in2 = (sc_int<8> ) (SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1
                                         .read());
  }
}
// resource: mux_8bx2i
void SobelFilter::drive_SobelFilter_Mul_8Sx8U_16S_4_20_in1(){
  if ( gs_ctrl2.read() ) {
    SobelFilter_Mul_8Sx8U_16S_4_20_in1 = (sc_uint<8> ) (s_reg_36.read().range(23
                                         ,16));
  } else {
    SobelFilter_Mul_8Sx8U_16S_4_20_in1 = (sc_uint<8> )s_reg_36.read();
  }
}
// resource: SobelFilter_Mul_8Sx8U_16S_4  instance: SobelFilter_Mul_8Sx8U_16S_4_20
void SobelFilter::SobelFilter_Mul_8Sx8U_16S_4_20(){
  SobelFilter_Mul_8Sx8U_16S_4_20_out1 = SobelFilter_Mul_8Sx8U_16S_4_20_in2
                                        .read() * 
                                        SobelFilter_Mul_8Sx8U_16S_4_20_in1
                                        .read();
}
// resource: mux_32bx2i
void SobelFilter::drive_SobelFilter_Add_32Sx16S_32S_4_21_in2(){
  if ( gs_ctrl4.read() ) {
    SobelFilter_Add_32Sx16S_32S_4_21_in2 = (sc_int<32> ) (s_reg_34.read());
  } else {
    SobelFilter_Add_32Sx16S_32S_4_21_in2 = (sc_int<32> ) (s_reg_32.read());
  }
}
// resource: mux_16bx2i
void SobelFilter::drive_SobelFilter_Add_32Sx16S_32S_4_21_in1(){
  if ( gs_ctrl5.read() ) {
    SobelFilter_Add_32Sx16S_32S_4_21_in1 = 128LL;
  } else {
    SobelFilter_Add_32Sx16S_32S_4_21_in1 = SobelFilter_Mul_8Sx8U_16S_4_20_out1
                                           .read();
  }
}
// resource: SobelFilter_Add_32Sx16S_32S_4  instance: SobelFilter_Add_32Sx16S_32S_4_21
void SobelFilter::SobelFilter_Add_32Sx16S_32S_4_21(){
  SobelFilter_Add_32Sx16S_32S_4_21_out1 = (/*cliff*/sc_int<32>)(
                                          SobelFilter_Add_32Sx16S_32S_4_21_in2
                                          .read() + 
                                          SobelFilter_Add_32Sx16S_32S_4_21_in1
                                          .read());
}
void SobelFilter::drive_SobelFilter_Mul_8Sx8U_16S_4_22_in1(){
  SobelFilter_Mul_8Sx8U_16S_4_22_in1 = (sc_uint<8> ) (s_reg_36.read().range(15,8
                                       ));
}
// resource: SobelFilter_Mul_8Sx8U_16S_4  instance: SobelFilter_Mul_8Sx8U_16S_4_22
void SobelFilter::SobelFilter_Mul_8Sx8U_16S_4_22(){
  SobelFilter_Mul_8Sx8U_16S_4_22_out1 = (sc_int<8> )SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1
                                        .read() * 
                                        SobelFilter_Mul_8Sx8U_16S_4_22_in1
                                        .read();
}
// resource: mux_16bx2i
void SobelFilter::drive_SobelFilter_Add_32Sx16S_32S_4_23_in1(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add_32Sx16S_32S_4_23_in1 = 128LL;
  } else {
    SobelFilter_Add_32Sx16S_32S_4_23_in1 = SobelFilter_Mul_8Sx8U_16S_4_22_out1
                                           .read();
  }
}
// resource: SobelFilter_Add_32Sx16S_32S_4  instance: SobelFilter_Add_32Sx16S_32S_4_23
void SobelFilter::SobelFilter_Add_32Sx16S_32S_4_23(){
  SobelFilter_Add_32Sx16S_32S_4_23_out1 = (/*cliff*/sc_int<32>)((sc_int<32> )
                                          s_reg_33.read() + 
                                          SobelFilter_Add_32Sx16S_32S_4_23_in1
                                          .read());
}
// resource: SobelFilter_LessThan_2Ux2U_1U_4  instance: SobelFilter_LessThan_2Ux2U_1U_4_26
void SobelFilter::SobelFilter_LessThan_2Ux2U_1U_4_26(){
  SobelFilter_LessThan_2Ux2U_1U_4_26_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                            s_reg_35.read() < (sc_uint<2> )3ULL)
  ;
}
// resource: SobelFilter_LessThan_2Ux2U_1U_4  instance: SobelFilter_LessThan_2Ux2U_1U_4_27
void SobelFilter::SobelFilter_LessThan_2Ux2U_1U_4_27(){
  SobelFilter_LessThan_2Ux2U_1U_4_27_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )
                                            s_reg_31.read() < (sc_uint<2> )3ULL)
  ;
}
void SobelFilter::drive_SobelFilter_N_Mux_32_2_1_4_30_ctrl1(){
  SobelFilter_N_Mux_32_2_1_4_30_ctrl1 = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                                        SobelFilter_Add_32Sx16S_32S_4_21_out1
                                        .read().range(31,31)));
}
// resource: SobelFilter_N_Mux_32_2_1_4
void SobelFilter::SobelFilter_N_Mux_32_2_1_4_30(){
  if ( SobelFilter_N_Mux_32_2_1_4_30_ctrl1.read() ) {
    SobelFilter_N_Mux_32_2_1_4_30_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_32_2_1_4_30_out1 = (sc_uint<32> ) (
                                         SobelFilter_Add_32Sx16S_32S_4_21_out1
                                         .read());
  }
}
// resource: mux_32bx2i
void SobelFilter::drive_SobelFilter_LessThan_32Sx9S_1U_4_31_in2(){
  if ( gs_ctrl7.read() ) {
    SobelFilter_LessThan_32Sx9S_1U_4_31_in2 = (sc_int<32> ) (s_reg_32.read());
  } else {
    SobelFilter_LessThan_32Sx9S_1U_4_31_in2 = (sc_int<32> ) (
                                              SobelFilter_N_Mux_32_2_1_4_30_out1
                                              .read());
  }
}
// resource: SobelFilter_LessThan_32Sx9S_1U_4  instance: SobelFilter_LessThan_32Sx9S_1U_4_31
void SobelFilter::SobelFilter_LessThan_32Sx9S_1U_4_31(){
  SobelFilter_LessThan_32Sx9S_1U_4_31_out1 = (/*imp*/sc_uint<1>)(SobelFilter_LessThan_32Sx9S_1U_4_31_in2
                                             .read() < (sc_int<9> )255LL);
}
void SobelFilter::drive_SobelFilter_N_Mux_32_2_1_4_32_ctrl1(){
  SobelFilter_N_Mux_32_2_1_4_32_ctrl1 = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                                        SobelFilter_Add_32Sx16S_32S_4_23_out1
                                        .read().range(31,31)));
}
// resource: SobelFilter_N_Mux_32_2_1_4
void SobelFilter::SobelFilter_N_Mux_32_2_1_4_32(){
  if ( SobelFilter_N_Mux_32_2_1_4_32_ctrl1.read() ) {
    SobelFilter_N_Mux_32_2_1_4_32_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_32_2_1_4_32_out1 = (sc_uint<32> ) (
                                         SobelFilter_Add_32Sx16S_32S_4_23_out1
                                         .read());
  }
}
// resource: SobelFilter_N_Mux_8_2_2_4
void SobelFilter::SobelFilter_N_Mux_8_2_2_4_33(){
  if ( SobelFilter_N_Mux_32_2_1_4_30_ctrl1.read() ) {
    SobelFilter_N_Mux_8_2_2_4_33_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_8_2_2_4_33_out1 = (sc_uint<8> )
                                        SobelFilter_Add_32Sx16S_32S_4_21_out1
                                        .read();
  }
}
// resource: SobelFilter_N_Mux_8_2_3_4
void SobelFilter::SobelFilter_N_Mux_8_2_3_4_34(){
  if ( SobelFilter_LessThan_32Sx9S_1U_4_31_out1.read() ) {
    SobelFilter_N_Mux_8_2_3_4_34_out1 = SobelFilter_N_Mux_8_2_2_4_33_out1.read()
    ;
  } else {
    SobelFilter_N_Mux_8_2_3_4_34_out1 = 255ULL;
  }
}
// resource: SobelFilter_N_Mux_8_2_2_4
void SobelFilter::SobelFilter_N_Mux_8_2_2_4_35(){
  if ( SobelFilter_N_Mux_32_2_1_4_32_ctrl1.read() ) {
    SobelFilter_N_Mux_8_2_2_4_35_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_8_2_2_4_35_out1 = (sc_uint<8> )
                                        SobelFilter_Add_32Sx16S_32S_4_23_out1
                                        .read();
  }
}
// resource: SobelFilter_N_Mux_8_2_3_4
void SobelFilter::SobelFilter_N_Mux_8_2_3_4_41(){
  if ( s_reg_37.read() ) {
    SobelFilter_N_Mux_8_2_3_4_41_out1 = (sc_uint<8> ) (o_newG_data.read());
  } else {
    SobelFilter_N_Mux_8_2_3_4_41_out1 = 255ULL;
  }
}
// resource: SobelFilter_N_Mux_8_2_3_4
void SobelFilter::SobelFilter_N_Mux_8_2_3_4_42(){
  if ( s_reg_37.read() ) {
    SobelFilter_N_Mux_8_2_3_4_42_out1 = (sc_uint<8> ) (o_newB_data.read());
  } else {
    SobelFilter_N_Mux_8_2_3_4_42_out1 = 255ULL;
  }
}
// resource: regr_4b
void SobelFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      global_state = global_state_next.read();
    }
  }
}
// resource: mux_4bx2i
void SobelFilter::drive_global_state_next(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 9ULL: 
    global_state_next = 1ULL;
    break;
  case 4ULL: 
    if ( s_reg_37.read() ) {
      global_state_next = 1ULL;
    } else {
      if ( SobelFilter_LessThan_2Ux2U_1U_4_27_out1.read() ) {
        global_state_next = 1ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 4ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_gs_ctrl2(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl2 = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl2 = 0ULL;
        break;
      case 3ULL: 
        gs_ctrl2 = 1ULL;
        break;
      }
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_gs_ctrl4(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl4 = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl4 = 0ULL;
        break;
      case 3ULL: case 5ULL: 
        gs_ctrl4 = 1ULL;
        break;
      }
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_gs_ctrl5(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl5 = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl5 = 0ULL;
        break;
      case 4ULL: case 5ULL: 
        gs_ctrl5 = 1ULL;
        break;
      }
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_gs_ctrl7(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl7 = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl7 = 0ULL;
        break;
      case 5ULL: case 6ULL: 
        gs_ctrl7 = 1ULL;
        break;
      }
    }
  }
}
void SobelFilter::drive_i_rgb_busy(){
  i_rgb_busy = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_44_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_43
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_43(){
  SobelFilter_Or_1Ux1U_1U_4_43_out1 = i_rgb_m_unvalidated_req.read() | i_rgb_vld
                                      .read();
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_44
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_44(){
  SobelFilter_And_1Ux1U_1U_4_44_out1 = (sc_uint<1> ) (
                                       SobelFilter_Or_1Ux1U_1U_4_43_out1.read()
                                        & (sc_uint<1> )i_rgb_m_busy_req_0.read()
                                       );
}
// resource: SobelFilter_Not_1U_1U_4  instance: SobelFilter_Not_1U_1U_4_45
void SobelFilter::SobelFilter_Not_1U_1U_4_45(){
  SobelFilter_Not_1U_1U_4_45_out1 = !SobelFilter_And_1Ux1U_1U_4_44_out1.read();
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_46
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_46(){
  SobelFilter_And_1Ux1U_1U_4_46_out1 = (sc_uint<1> ) (
                                       SobelFilter_Not_1U_1U_4_45_out1.read() & 
                                       (sc_uint<1> )i_rgb_vld.read());
}
// resource: SobelFilter_Not_1U_1U_4  instance: SobelFilter_Not_1U_1U_4_47
void SobelFilter::SobelFilter_Not_1U_1U_4_47(){
  SobelFilter_Not_1U_1U_4_47_out1 = !SobelFilter_And_1Ux1U_1U_4_46_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_i_rgb_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_unvalidated_req = 1ULL;
  } else {
    i_rgb_m_unvalidated_req = (sc_uint<1> ) (SobelFilter_N_Muxb_1_2_4_4_10_out1
                              .read());
  }
}
// resource: SobelFilter_N_Muxb_1_2_4_4
void SobelFilter::SobelFilter_N_Muxb_1_2_4_4_10(){
  if ( i_rgb_m_busy_req_0.read() ) {
    SobelFilter_N_Muxb_1_2_4_4_10_out1 = (sc_uint<1> ) (i_rgb_m_unvalidated_req
                                         .read());
  } else {
    SobelFilter_N_Muxb_1_2_4_4_10_out1 = (sc_uint<1> ) (i_rgb_vld.read());
  }
}
void SobelFilter::drive_o_newR_vld(){
  o_newR_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_2
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_2(){
  SobelFilter_Or_1Ux1U_1U_4_2_out1 = o_newR_m_unacked_req.read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_4_1_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_o_newR_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newR_m_unacked_req = 0ULL;
  } else {
    o_newR_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_13_out1
                           .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_13
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_13(){
  SobelFilter_And_1Ux1U_1U_4_13_out1 = (sc_uint<1> ) (o_newR_busy.read() & 
                                       o_newR_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_4  instance: SobelFilter_Xor_1Ux1U_1U_4_1
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_4_1(){
  SobelFilter_Xor_1Ux1U_1U_4_1_out1 = (sc_uint<1> ) (o_newR_m_req_m_trig_req
                                      .read() ^ o_newR_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_1b
void SobelFilter::drive_o_newR_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newR_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_newR_m_req_m_prev_trig_req = o_newR_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_4  instance: SobelFilter_Not_1U_1U_4_3
void SobelFilter::SobelFilter_Not_1U_1U_4_3(){
  SobelFilter_Not_1U_1U_4_3_out1 = !o_newR_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_newG_vld(){
  o_newG_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_5_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_5
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_5(){
  SobelFilter_Or_1Ux1U_1U_4_5_out1 = o_newG_m_unacked_req.read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_4_4_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_o_newG_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newG_m_unacked_req = 0ULL;
  } else {
    o_newG_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_14_out1
                           .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_14
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_14(){
  SobelFilter_And_1Ux1U_1U_4_14_out1 = (sc_uint<1> ) (o_newG_busy.read() & 
                                       o_newG_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_4  instance: SobelFilter_Xor_1Ux1U_1U_4_4
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_4_4(){
  SobelFilter_Xor_1Ux1U_1U_4_4_out1 = (sc_uint<1> ) (o_newG_m_req_m_trig_req
                                      .read() ^ o_newG_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_1b
void SobelFilter::drive_o_newG_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newG_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_newG_m_req_m_prev_trig_req = o_newG_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_4  instance: SobelFilter_Not_1U_1U_4_6
void SobelFilter::SobelFilter_Not_1U_1U_4_6(){
  SobelFilter_Not_1U_1U_4_6_out1 = !o_newG_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_newB_vld(){
  o_newB_vld = (sc_uint<1> ) (SobelFilter_Or_1Ux1U_1U_4_8_out1.read());
}
// resource: SobelFilter_Or_1Ux1U_1U_4  instance: SobelFilter_Or_1Ux1U_1U_4_8
void SobelFilter::SobelFilter_Or_1Ux1U_1U_4_8(){
  SobelFilter_Or_1Ux1U_1U_4_8_out1 = o_newB_m_unacked_req.read() | (sc_uint<1>)
                                     SobelFilter_Xor_1Ux1U_1U_4_7_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_o_newB_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newB_m_unacked_req = 0ULL;
  } else {
    o_newB_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1Ux1U_1U_4_15_out1
                           .read());
  }
}
// resource: SobelFilter_And_1Ux1U_1U_4  instance: SobelFilter_And_1Ux1U_1U_4_15
void SobelFilter::SobelFilter_And_1Ux1U_1U_4_15(){
  SobelFilter_And_1Ux1U_1U_4_15_out1 = (sc_uint<1> ) (o_newB_busy.read() & 
                                       o_newB_vld.read());
}
// resource: SobelFilter_Xor_1Ux1U_1U_4  instance: SobelFilter_Xor_1Ux1U_1U_4_7
void SobelFilter::SobelFilter_Xor_1Ux1U_1U_4_7(){
  SobelFilter_Xor_1Ux1U_1U_4_7_out1 = (sc_uint<1> ) (o_newB_m_req_m_trig_req
                                      .read() ^ o_newB_m_req_m_prev_trig_req
                                      .read());
}
// resource: regr_1b
void SobelFilter::drive_o_newB_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newB_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_newB_m_req_m_prev_trig_req = o_newB_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1U_4  instance: SobelFilter_Not_1U_1U_4_9
void SobelFilter::SobelFilter_Not_1U_1U_4_9(){
  SobelFilter_Not_1U_1U_4_9_out1 = !o_newB_m_req_m_trig_req.read();
}
