// Generated by stratus_hls 17.21-s100  (88813.070850)
// Sun Nov 17 10:14:34 2019
// from ../SobelFilter.cpp
#include "SobelFilter_rtl.h"

struct SobelFilter;
SobelFilter::SobelFilter(sc_module_name name) : sc_module(name) 
    ,i_clk("i_clk")
    ,i_rst("i_rst")
    ,i_rgb_busy("i_rgb_busy")
    ,i_rgb_vld("i_rgb_vld")
    ,i_rgb_data("i_rgb_data")
    ,o_newR_busy("o_newR_busy")
    ,o_newR_vld("o_newR_vld")
    ,o_newR_data("o_newR_data")
    ,o_newG_busy("o_newG_busy")
    ,o_newG_vld("o_newG_vld")
    ,o_newG_data("o_newG_data")
    ,o_newB_busy("o_newB_busy")
    ,o_newB_vld("o_newB_vld")
    ,o_newB_data("o_newB_data")
    ,o_newB_m_req_m_prev_trig_req("o_newB_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1U_11_4_7_out1("SobelFilter_Xor_1U_11_4_7_out1")
    ,o_newB_m_unacked_req("o_newB_m_unacked_req")
    ,SobelFilter_Or_1U_9_4_8_out1("SobelFilter_Or_1U_9_4_8_out1")
    ,o_newG_m_req_m_prev_trig_req("o_newG_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1U_11_4_4_out1("SobelFilter_Xor_1U_11_4_4_out1")
    ,o_newG_m_unacked_req("o_newG_m_unacked_req")
    ,SobelFilter_Or_1U_9_4_5_out1("SobelFilter_Or_1U_9_4_5_out1")
    ,o_newR_m_req_m_prev_trig_req("o_newR_m_req_m_prev_trig_req")
    ,SobelFilter_Xor_1U_11_4_1_out1("SobelFilter_Xor_1U_11_4_1_out1")
    ,o_newR_m_unacked_req("o_newR_m_unacked_req")
    ,SobelFilter_Or_1U_9_4_2_out1("SobelFilter_Or_1U_9_4_2_out1")
    ,SobelFilter_N_Muxb_1_2_14_4_10_out1("SobelFilter_N_Muxb_1_2_14_4_10_out1")
    ,SobelFilter_And_1U_6_4_42_out1("SobelFilter_And_1U_6_4_42_out1")
    ,SobelFilter_Not_1U_1_4_41_out1("SobelFilter_Not_1U_1_4_41_out1")
    ,SobelFilter_Or_1U_9_4_39_out1("SobelFilter_Or_1U_9_4_39_out1")
    ,i_rgb_m_unvalidated_req("i_rgb_m_unvalidated_req")
    ,SobelFilter_And_1U_6_4_40_out1("SobelFilter_And_1U_6_4_40_out1")
    ,global_state_next("global_state_next")
    ,SobelFilter_N_Mux_32_2_22_4_35_ctrl1("SobelFilter_N_Mux_32_2_22_4_35_ctrl1")
    ,SobelFilter_Add2i128s32_4_34_out1("SobelFilter_Add2i128s32_4_34_out1")
    ,SobelFilter_Add2Mul2s8u8s32_4_33_in2("SobelFilter_Add2Mul2s8u8s32_4_33_in2")
    ,SobelFilter_N_Mux_8_2_23_4_23_out1("SobelFilter_N_Mux_8_2_23_4_23_out1")
    ,SobelFilter_Lti255s32_4_22_out1("SobelFilter_Lti255s32_4_22_out1")
    ,SobelFilter_N_Mux_32_2_22_4_21_out1("SobelFilter_N_Mux_32_2_22_4_21_out1")
    ,SobelFilter_N_Mux_32_2_22_4_21_ctrl1("SobelFilter_N_Mux_32_2_22_4_21_ctrl1")
    ,SobelFilter_Add2i128s32_4_20_out1("SobelFilter_Add2i128s32_4_20_out1")
    ,SobelFilter_Add2Mul2s8u8s32_4_19_in1("SobelFilter_Add2Mul2s8u8s32_4_19_in1")
    ,SobelFilter_Add2Mul2s8u8s32_4_19_in2("SobelFilter_Add2Mul2s8u8s32_4_19_in2")
    ,SobelFilter_Add2Mul2s8u8s32_4_19_in3("SobelFilter_Add2Mul2s8u8s32_4_19_in3")
    ,gs_ctrl0("gs_ctrl0")
    ,s_reg_26("s_reg_26")
    ,SobelFilter_Add2i1u2_4_17_out1("SobelFilter_Add2i1u2_4_17_out1")
    ,SobelFilter_Add2i1u2_4_18_out1("SobelFilter_Add2i1u2_4_18_out1")
    ,s_reg_24("s_reg_24")
    ,SobelFilter_Add2Mul2s8u8s32_4_33_out1("SobelFilter_Add2Mul2s8u8s32_4_33_out1")
    ,s_reg_23("s_reg_23")
    ,SobelFilter_N_Mux_32_2_22_4_35_out1("SobelFilter_N_Mux_32_2_22_4_35_out1")
    ,s_reg_22("s_reg_22")
    ,SobelFilter_Add2Mul2s8u8s32_4_19_out1("SobelFilter_Add2Mul2s8u8s32_4_19_out1")
    ,s_reg_21("s_reg_21")
    ,SobelFilter_Lti255s32_4_37_out1("SobelFilter_Lti255s32_4_37_out1")
    ,s_reg_25("s_reg_25")
    ,s_reg_20("s_reg_20")
    ,SobelFilter_Not_1U_1_4_43_out1("SobelFilter_Not_1U_1_4_43_out1")
    ,SobelFilter_And_1U_6_4_13_out1("SobelFilter_And_1U_6_4_13_out1")
    ,SobelFilter_And_1U_6_4_14_out1("SobelFilter_And_1U_6_4_14_out1")
    ,SobelFilter_And_1U_6_4_15_out1("SobelFilter_And_1U_6_4_15_out1")
    ,SobelFilter_Not_1U_1_4_9_out1("SobelFilter_Not_1U_1_4_9_out1")
    ,o_newB_m_req_m_trig_req("o_newB_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1_4_6_out1("SobelFilter_Not_1U_1_4_6_out1")
    ,o_newG_m_req_m_trig_req("o_newG_m_req_m_trig_req")
    ,SobelFilter_Not_1U_1_4_3_out1("SobelFilter_Not_1U_1_4_3_out1")
    ,o_newR_m_req_m_trig_req("o_newR_m_req_m_trig_req")
    ,i_rgb_m_busy_req_0("i_rgb_m_busy_req_0")
    ,SobelFilter_N_Mux_8_2_24_4_24_out1("SobelFilter_N_Mux_8_2_24_4_24_out1")
    ,SobelFilter_N_Mux_8_2_24_4_38_out1("SobelFilter_N_Mux_8_2_24_4_38_out1")
    ,SobelFilter_N_Mux_8_2_23_4_36_out1("SobelFilter_N_Mux_8_2_23_4_36_out1")
    ,SobelFilter_Lti3u2_4_32_out1("SobelFilter_Lti3u2_4_32_out1")
    ,SobelFilter_Lti3u2_4_31_out1("SobelFilter_Lti3u2_4_31_out1")
    ,global_state("global_state")
    ,stall0("stall0")
    ,SobelFilter_Add2u2Mul2i3u2_4_16_out1("SobelFilter_Add2u2Mul2i3u2_4_16_out1")
    ,SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1("SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1")
{
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1 = new 
  SobelFilter_ROM_9X8_embossFilterMask(
  "SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1");
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1->in1(
  SobelFilter_Add2u2Mul2i3u2_4_16_out1);
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1->out1(
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1);
  SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1->clk(i_clk);

  SC_METHOD(drive_o_newB_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newG_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newR_data);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_m_busy_req_0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newR_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newG_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_o_newB_m_req_m_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_Not_1U_1_4_43_out1 );
  sensitive << ( SobelFilter_And_1U_6_4_13_out1 );
  sensitive << ( SobelFilter_And_1U_6_4_14_out1 );
  sensitive << ( SobelFilter_And_1U_6_4_15_out1 );

  SC_METHOD(drive_s_reg_20);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_21);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_22);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_23);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_24);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_25);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_s_reg_26);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Add2u2Mul2i3u2_4_16);
  sensitive << ( s_reg_20 );
  sensitive << ( s_reg_24 );

  SC_METHOD(SobelFilter_Add2i1u2_4_17);
  sensitive << ( s_reg_20 );

  SC_METHOD(SobelFilter_Add2i1u2_4_18);
  sensitive << ( s_reg_24 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s8u8s32_4_19_in3);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_22 );
  sensitive << ( s_reg_21 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s8u8s32_4_19_in2);
  sensitive << ( gs_ctrl0 );
  sensitive << ( s_reg_26 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s8u8s32_4_19_in1);
  sensitive << ( gs_ctrl0 );
  sensitive << ( o_newG_data );
  sensitive << ( SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1 );

  SC_METHOD(SobelFilter_Add2Mul2s8u8s32_4_19);
  sensitive << ( SobelFilter_Add2Mul2s8u8s32_4_19_in1 );
  sensitive << ( SobelFilter_Add2Mul2s8u8s32_4_19_in2 );
  sensitive << ( SobelFilter_Add2Mul2s8u8s32_4_19_in3 );

  SC_METHOD(SobelFilter_Add2i128s32_4_20);
  sensitive << ( SobelFilter_Add2Mul2s8u8s32_4_19_out1 );

  SC_METHOD(drive_SobelFilter_N_Mux_32_2_22_4_21_ctrl1);
  sensitive << ( SobelFilter_Add2i128s32_4_20_out1 );

  SC_METHOD(SobelFilter_N_Mux_32_2_22_4_21);
  sensitive << ( SobelFilter_N_Mux_32_2_22_4_21_ctrl1 );
  sensitive << ( SobelFilter_Add2i128s32_4_20_out1 );

  SC_METHOD(SobelFilter_Lti255s32_4_22);
  sensitive << ( SobelFilter_N_Mux_32_2_22_4_21_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_23_4_23);
  sensitive << ( SobelFilter_N_Mux_32_2_22_4_21_ctrl1 );
  sensitive << ( SobelFilter_Add2i128s32_4_20_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_24_4_24);
  sensitive << ( SobelFilter_Lti255s32_4_22_out1 );
  sensitive << ( SobelFilter_N_Mux_8_2_23_4_23_out1 );

  SC_METHOD(SobelFilter_Lti3u2_4_31);
  sensitive << ( s_reg_25 );

  SC_METHOD(SobelFilter_Lti3u2_4_32);
  sensitive << ( s_reg_24 );

  SC_METHOD(drive_SobelFilter_Add2Mul2s8u8s32_4_33_in2);
  sensitive << ( s_reg_26 );

  SC_METHOD(SobelFilter_Add2Mul2s8u8s32_4_33);
  sensitive << ( o_newG_data );
  sensitive << ( SobelFilter_Add2Mul2s8u8s32_4_33_in2 );
  sensitive << ( s_reg_23 );

  SC_METHOD(SobelFilter_Add2i128s32_4_34);
  sensitive << ( SobelFilter_Add2Mul2s8u8s32_4_33_out1 );

  SC_METHOD(drive_SobelFilter_N_Mux_32_2_22_4_35_ctrl1);
  sensitive << ( SobelFilter_Add2i128s32_4_34_out1 );

  SC_METHOD(SobelFilter_N_Mux_32_2_22_4_35);
  sensitive << ( SobelFilter_N_Mux_32_2_22_4_35_ctrl1 );
  sensitive << ( SobelFilter_Add2i128s32_4_34_out1 );

  SC_METHOD(SobelFilter_N_Mux_8_2_23_4_36);
  sensitive << ( SobelFilter_N_Mux_32_2_22_4_35_ctrl1 );
  sensitive << ( SobelFilter_Add2i128s32_4_34_out1 );

  SC_METHOD(SobelFilter_Lti255s32_4_37);
  sensitive << ( s_reg_22 );

  SC_METHOD(SobelFilter_N_Mux_8_2_24_4_38);
  sensitive << ( s_reg_20 );
  sensitive << ( o_newB_data );

  SC_METHOD(drive_global_state);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );
  sensitive << ( SobelFilter_Lti3u2_4_32_out1 );
  sensitive << ( SobelFilter_Lti3u2_4_31_out1 );

  SC_METHOD(drive_gs_ctrl0);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(drive_i_rgb_busy);
  sensitive << ( SobelFilter_And_1U_6_4_40_out1 );

  SC_METHOD(SobelFilter_Or_1U_9_4_39);
  sensitive << ( i_rgb_vld );
  sensitive << ( i_rgb_m_unvalidated_req );

  SC_METHOD(SobelFilter_And_1U_6_4_40);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( SobelFilter_Or_1U_9_4_39_out1 );

  SC_METHOD(SobelFilter_Not_1U_1_4_41);
  sensitive << ( SobelFilter_And_1U_6_4_40_out1 );

  SC_METHOD(SobelFilter_And_1U_6_4_42);
  sensitive << ( i_rgb_vld );
  sensitive << ( SobelFilter_Not_1U_1_4_41_out1 );

  SC_METHOD(SobelFilter_Not_1U_1_4_43);
  sensitive << ( SobelFilter_And_1U_6_4_42_out1 );

  SC_METHOD(drive_i_rgb_m_unvalidated_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_N_Muxb_1_2_14_4_10);
  sensitive << ( i_rgb_m_busy_req_0 );
  sensitive << ( i_rgb_m_unvalidated_req );
  sensitive << ( i_rgb_vld );

  SC_METHOD(drive_o_newR_vld);
  sensitive << ( SobelFilter_Or_1U_9_4_2_out1 );

  SC_METHOD(SobelFilter_Or_1U_9_4_2);
  sensitive << ( SobelFilter_Xor_1U_11_4_1_out1 );
  sensitive << ( o_newR_m_unacked_req );

  SC_METHOD(drive_o_newR_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1U_6_4_13);
  sensitive << ( o_newR_vld );
  sensitive << ( o_newR_busy );

  SC_METHOD(SobelFilter_Xor_1U_11_4_1);
  sensitive << ( o_newR_m_req_m_prev_trig_req );
  sensitive << ( o_newR_m_req_m_trig_req );

  SC_METHOD(drive_o_newR_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1_4_3);
  sensitive << ( o_newR_m_req_m_trig_req );

  SC_METHOD(drive_o_newG_vld);
  sensitive << ( SobelFilter_Or_1U_9_4_5_out1 );

  SC_METHOD(SobelFilter_Or_1U_9_4_5);
  sensitive << ( SobelFilter_Xor_1U_11_4_4_out1 );
  sensitive << ( o_newG_m_unacked_req );

  SC_METHOD(drive_o_newG_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1U_6_4_14);
  sensitive << ( o_newG_vld );
  sensitive << ( o_newG_busy );

  SC_METHOD(SobelFilter_Xor_1U_11_4_4);
  sensitive << ( o_newG_m_req_m_prev_trig_req );
  sensitive << ( o_newG_m_req_m_trig_req );

  SC_METHOD(drive_o_newG_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1_4_6);
  sensitive << ( o_newG_m_req_m_trig_req );

  SC_METHOD(drive_o_newB_vld);
  sensitive << ( SobelFilter_Or_1U_9_4_8_out1 );

  SC_METHOD(SobelFilter_Or_1U_9_4_8);
  sensitive << ( SobelFilter_Xor_1U_11_4_7_out1 );
  sensitive << ( o_newB_m_unacked_req );

  SC_METHOD(drive_o_newB_m_unacked_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_And_1U_6_4_15);
  sensitive << ( o_newB_vld );
  sensitive << ( o_newB_busy );

  SC_METHOD(SobelFilter_Xor_1U_11_4_7);
  sensitive << ( o_newB_m_req_m_prev_trig_req );
  sensitive << ( o_newB_m_req_m_trig_req );

  SC_METHOD(drive_o_newB_m_req_m_prev_trig_req);
  sensitive << i_clk.pos();
  dont_initialize();

  SC_METHOD(SobelFilter_Not_1U_1_4_9);
  sensitive << ( o_newB_m_req_m_trig_req );

}
// resource: mux_8bx2i
// resource: regr_8b
void SobelFilter::drive_o_newB_data(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 3ULL: 
      if ( (!SobelFilter_Lti3u2_4_32_out1.read() && !
           SobelFilter_Lti3u2_4_31_out1.read()) ) {
        o_newB_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_23_4_36_out1.read());
      } 
      break;
    case 6ULL: 
      o_newB_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_24_4_38_out1.read());
      break;
    }
  }
}
// resource: mux_8bx2i
// resource: regr_8b
void SobelFilter::drive_o_newG_data(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 2ULL: 
      o_newG_data = SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1
                    .read();
      break;
    case 3ULL: 
      if ( (!SobelFilter_Lti3u2_4_32_out1.read() && !
           SobelFilter_Lti3u2_4_31_out1.read()) ) {
        o_newG_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_24_4_24_out1.read());
      } 
      break;
    }
  }
}
// resource: regr_8b
void SobelFilter::drive_o_newR_data(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 2ULL: 
      o_newR_data = (sc_uint<8> ) (SobelFilter_N_Mux_8_2_24_4_24_out1.read());
      break;
    }
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_i_rgb_m_busy_req_0(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_busy_req_0 = 1ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 0ULL: case 8ULL: 
        i_rgb_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: 
        i_rgb_m_busy_req_0 = 1ULL;
        break;
      case 3ULL: 
        if ( SobelFilter_Lti3u2_4_32_out1.read() ) {
          i_rgb_m_busy_req_0 = 0ULL;
        } else {
          if ( SobelFilter_Lti3u2_4_31_out1.read() ) {
            i_rgb_m_busy_req_0 = 0ULL;
          } 
        }
        break;
      }
    }
  }
}
// resource: regr_1b
void SobelFilter::drive_o_newR_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newR_m_req_m_trig_req = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 4ULL: 
        o_newR_m_req_m_trig_req = (sc_uint<1> ) (SobelFilter_Not_1U_1_4_3_out1
                                  .read());
        break;
      }
    }
  }
}
// resource: regr_1b
void SobelFilter::drive_o_newG_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newG_m_req_m_trig_req = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 5ULL: 
        o_newG_m_req_m_trig_req = (sc_uint<1> ) (SobelFilter_Not_1U_1_4_6_out1
                                  .read());
        break;
      }
    }
  }
}
// resource: regr_1b
void SobelFilter::drive_o_newB_m_req_m_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newB_m_req_m_trig_req = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state.read()) ) {
      case 6ULL: 
        o_newB_m_req_m_trig_req = (sc_uint<1> ) (SobelFilter_Not_1U_1_4_9_out1
                                  .read());
        break;
      }
    }
  }
}
// resource: mux_1bx5i
void SobelFilter::drive_stall0(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: 
    stall0 = SobelFilter_Not_1U_1_4_43_out1.read();
    break;
  case 5ULL: 
    stall0 = SobelFilter_And_1U_6_4_13_out1.read();
    break;
  case 6ULL: 
    stall0 = SobelFilter_And_1U_6_4_14_out1.read();
    break;
  case 7ULL: 
    stall0 = SobelFilter_And_1U_6_4_15_out1.read();
    break;
  }
}
// resource: mux_2bx3i
// resource: regr_2b
void SobelFilter::drive_s_reg_20(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 8ULL: 
      s_reg_20 = 0ULL;
      break;
    case 3ULL: 
      if ( SobelFilter_Lti3u2_4_32_out1.read() );
      else {
        s_reg_20 = s_reg_25.read();
      }
      break;
    case 4ULL: 
      s_reg_20 = (sc_uint<2> ) (SobelFilter_Lti255s32_4_37_out1.read());
      break;
    }
  }
}
// resource: mux_32bx2i
// resource: regr_32b
void SobelFilter::drive_s_reg_21(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 8ULL: 
      s_reg_21 = 0ULL;
      break;
    case 2ULL: 
      s_reg_21 = (sc_uint<32> ) (SobelFilter_Add2Mul2s8u8s32_4_19_out1.read());
      break;
    }
  }
}
// resource: mux_32bx3i
// resource: regr_32b
void SobelFilter::drive_s_reg_22(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 8ULL: 
      s_reg_22 = 0ULL;
      break;
    case 3ULL: 
      if ( SobelFilter_Lti3u2_4_32_out1.read() ) {
        s_reg_22 = (sc_uint<32> ) (SobelFilter_Add2Mul2s8u8s32_4_19_out1.read())
        ;
      } else {
        if ( SobelFilter_Lti3u2_4_31_out1.read() ) {
          s_reg_22 = (sc_uint<32> ) (SobelFilter_Add2Mul2s8u8s32_4_19_out1
                     .read());
        } else {
          s_reg_22 = (sc_uint<32> ) (SobelFilter_N_Mux_32_2_22_4_35_out1.read())
          ;
        }
      }
      break;
    }
  }
}
// resource: mux_32bx2i
// resource: regr_32b
void SobelFilter::drive_s_reg_23(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 8ULL: 
      s_reg_23 = 0ULL;
      break;
    case 3ULL: 
      s_reg_23 = (sc_uint<32> ) (SobelFilter_Add2Mul2s8u8s32_4_33_out1.read());
      break;
    }
  }
}
// resource: mux_2bx2i
// resource: regr_2b
void SobelFilter::drive_s_reg_24(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 0ULL: case 8ULL: 
      s_reg_24 = 0ULL;
      break;
    case 1ULL: 
      s_reg_24 = (sc_uint<2> ) (SobelFilter_Add2i1u2_4_18_out1.read());
      break;
    case 3ULL: 
      if ( SobelFilter_Lti3u2_4_32_out1.read() );
      else {
        s_reg_24 = 0ULL;
      }
      break;
    }
  }
}
// resource: regr_2b
void SobelFilter::drive_s_reg_25(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 1ULL: 
      s_reg_25 = (sc_uint<2> ) (SobelFilter_Add2i1u2_4_17_out1.read());
      break;
    }
  }
}
// resource: regr_24b
void SobelFilter::drive_s_reg_26(){
  if ( stall0.read() );
  else {
    switch( (sc_uint<4>)(global_state.read()) ) {
    case 1ULL: 
      s_reg_26 = i_rgb_data.read();
      break;
    }
  }
}
// resource: SobelFilter_Add2u2Mul2i3u2_4  instance: SobelFilter_Add2u2Mul2i3u2_4_16
void SobelFilter::SobelFilter_Add2u2Mul2i3u2_4_16(){
  SobelFilter_Add2u2Mul2i3u2_4_16_out1 = (s_reg_24.read() * 3ULL + s_reg_20
                                         .read());
}
// resource: SobelFilter_Add2i1u2_4  instance: SobelFilter_Add2i1u2_4_17
void SobelFilter::SobelFilter_Add2i1u2_4_17(){
  SobelFilter_Add2i1u2_4_17_out1 = (/*cliff*/sc_int<32>)((sc_uint<2> )s_reg_20
                                   .read() + 1LL);
}
// resource: SobelFilter_Add2i1u2_4  instance: SobelFilter_Add2i1u2_4_18
void SobelFilter::SobelFilter_Add2i1u2_4_18(){
  SobelFilter_Add2i1u2_4_18_out1 = (/*cliff*/sc_int<32>)((sc_uint<2> )s_reg_24
                                   .read() + 1LL);
}
// resource: mux_32bx2i
void SobelFilter::drive_SobelFilter_Add2Mul2s8u8s32_4_19_in3(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add2Mul2s8u8s32_4_19_in3 = (sc_int<32> ) (s_reg_22.read());
  } else {
    SobelFilter_Add2Mul2s8u8s32_4_19_in3 = (sc_int<32> ) (s_reg_21.read());
  }
}
// resource: mux_8bx2i
void SobelFilter::drive_SobelFilter_Add2Mul2s8u8s32_4_19_in2(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add2Mul2s8u8s32_4_19_in2 = (sc_uint<8> ) (s_reg_26.read().range(
                                           15,8));
  } else {
    SobelFilter_Add2Mul2s8u8s32_4_19_in2 = (sc_uint<8> )s_reg_26.read();
  }
}
// resource: mux_8bx2i
void SobelFilter::drive_SobelFilter_Add2Mul2s8u8s32_4_19_in1(){
  if ( gs_ctrl0.read() ) {
    SobelFilter_Add2Mul2s8u8s32_4_19_in1 = (sc_int<8> ) (o_newG_data.read());
  } else {
    SobelFilter_Add2Mul2s8u8s32_4_19_in1 = (sc_int<8> ) (SobelFilter_ROM_9X8_embossFilterMask_embossFilterMask_1_out1
                                           .read());
  }
}
// resource: SobelFilter_Add2Mul2s8u8s32_4  instance: SobelFilter_Add2Mul2s8u8s32_4_19
void SobelFilter::SobelFilter_Add2Mul2s8u8s32_4_19(){
  SobelFilter_Add2Mul2s8u8s32_4_19_out1 = (/*cliff*/sc_int<32>)(
                                          SobelFilter_Add2Mul2s8u8s32_4_19_in3
                                          .read() + 
                                          SobelFilter_Add2Mul2s8u8s32_4_19_in2
                                          .read() * 
                                          SobelFilter_Add2Mul2s8u8s32_4_19_in1
                                          .read());
}
// resource: SobelFilter_Add2i128s32_4  instance: SobelFilter_Add2i128s32_4_20
void SobelFilter::SobelFilter_Add2i128s32_4_20(){
  SobelFilter_Add2i128s32_4_20_out1 = (/*cliff*/sc_int<32>)(
                                      SobelFilter_Add2Mul2s8u8s32_4_19_out1
                                      .read() + 128LL);
}
void SobelFilter::drive_SobelFilter_N_Mux_32_2_22_4_21_ctrl1(){
  SobelFilter_N_Mux_32_2_22_4_21_ctrl1 = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                                         SobelFilter_Add2i128s32_4_20_out1
                                         .read().range(31,31)));
}
// resource: SobelFilter_N_Mux_32_2_22_4
void SobelFilter::SobelFilter_N_Mux_32_2_22_4_21(){
  if ( SobelFilter_N_Mux_32_2_22_4_21_ctrl1.read() ) {
    SobelFilter_N_Mux_32_2_22_4_21_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_32_2_22_4_21_out1 = (sc_uint<32> ) (
                                          SobelFilter_Add2i128s32_4_20_out1
                                          .read());
  }
}
// resource: SobelFilter_Lti255s32_4  instance: SobelFilter_Lti255s32_4_22
void SobelFilter::SobelFilter_Lti255s32_4_22(){
  SobelFilter_Lti255s32_4_22_out1 = (/*imp*/sc_uint<1>)((sc_int<32> )
                                    SobelFilter_N_Mux_32_2_22_4_21_out1.read()
                                     < (sc_int<9> )255LL);
}
// resource: SobelFilter_N_Mux_8_2_23_4
void SobelFilter::SobelFilter_N_Mux_8_2_23_4_23(){
  if ( SobelFilter_N_Mux_32_2_22_4_21_ctrl1.read() ) {
    SobelFilter_N_Mux_8_2_23_4_23_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_8_2_23_4_23_out1 = (sc_uint<8> )
                                         SobelFilter_Add2i128s32_4_20_out1
                                         .read();
  }
}
// resource: SobelFilter_N_Mux_8_2_24_4
void SobelFilter::SobelFilter_N_Mux_8_2_24_4_24(){
  if ( SobelFilter_Lti255s32_4_22_out1.read() ) {
    SobelFilter_N_Mux_8_2_24_4_24_out1 = SobelFilter_N_Mux_8_2_23_4_23_out1
                                         .read();
  } else {
    SobelFilter_N_Mux_8_2_24_4_24_out1 = 255ULL;
  }
}
// resource: SobelFilter_Lti3u2_4  instance: SobelFilter_Lti3u2_4_31
void SobelFilter::SobelFilter_Lti3u2_4_31(){
  SobelFilter_Lti3u2_4_31_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )s_reg_25
                                 .read() < (sc_uint<2> )3ULL);
}
// resource: SobelFilter_Lti3u2_4  instance: SobelFilter_Lti3u2_4_32
void SobelFilter::SobelFilter_Lti3u2_4_32(){
  SobelFilter_Lti3u2_4_32_out1 = (/*imp*/sc_uint<1>)((sc_uint<2> )s_reg_24
                                 .read() < (sc_uint<2> )3ULL);
}
void SobelFilter::drive_SobelFilter_Add2Mul2s8u8s32_4_33_in2(){
  SobelFilter_Add2Mul2s8u8s32_4_33_in2 = (sc_uint<8> ) (s_reg_26.read().range(23
                                         ,16));
}
// resource: SobelFilter_Add2Mul2s8u8s32_4  instance: SobelFilter_Add2Mul2s8u8s32_4_33
void SobelFilter::SobelFilter_Add2Mul2s8u8s32_4_33(){
  SobelFilter_Add2Mul2s8u8s32_4_33_out1 = (/*cliff*/sc_int<32>)((sc_int<32> )
                                          s_reg_23.read() + 
                                          SobelFilter_Add2Mul2s8u8s32_4_33_in2
                                          .read() * (sc_int<8> )o_newG_data
                                          .read());
}
// resource: SobelFilter_Add2i128s32_4  instance: SobelFilter_Add2i128s32_4_34
void SobelFilter::SobelFilter_Add2i128s32_4_34(){
  SobelFilter_Add2i128s32_4_34_out1 = (/*cliff*/sc_int<32>)(
                                      SobelFilter_Add2Mul2s8u8s32_4_33_out1
                                      .read() + 128LL);
}
void SobelFilter::drive_SobelFilter_N_Mux_32_2_22_4_35_ctrl1(){
  SobelFilter_N_Mux_32_2_22_4_35_ctrl1 = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) 
                                         SobelFilter_Add2i128s32_4_34_out1
                                         .read().range(31,31)));
}
// resource: SobelFilter_N_Mux_32_2_22_4
void SobelFilter::SobelFilter_N_Mux_32_2_22_4_35(){
  if ( SobelFilter_N_Mux_32_2_22_4_35_ctrl1.read() ) {
    SobelFilter_N_Mux_32_2_22_4_35_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_32_2_22_4_35_out1 = (sc_uint<32> ) (
                                          SobelFilter_Add2i128s32_4_34_out1
                                          .read());
  }
}
// resource: SobelFilter_N_Mux_8_2_23_4
void SobelFilter::SobelFilter_N_Mux_8_2_23_4_36(){
  if ( SobelFilter_N_Mux_32_2_22_4_35_ctrl1.read() ) {
    SobelFilter_N_Mux_8_2_23_4_36_out1 = 0ULL;
  } else {
    SobelFilter_N_Mux_8_2_23_4_36_out1 = (sc_uint<8> )
                                         SobelFilter_Add2i128s32_4_34_out1
                                         .read();
  }
}
// resource: SobelFilter_Lti255s32_4  instance: SobelFilter_Lti255s32_4_37
void SobelFilter::SobelFilter_Lti255s32_4_37(){
  SobelFilter_Lti255s32_4_37_out1 = (/*imp*/sc_uint<1>)((sc_int<32> )s_reg_22
                                    .read() < (sc_int<9> )255LL);
}
// resource: SobelFilter_N_Mux_8_2_24_4
void SobelFilter::SobelFilter_N_Mux_8_2_24_4_38(){
  if ( (sc_uint<1> )s_reg_20.read() ) {
    SobelFilter_N_Mux_8_2_24_4_38_out1 = (sc_uint<8> ) (o_newB_data.read());
  } else {
    SobelFilter_N_Mux_8_2_24_4_38_out1 = 255ULL;
  }
}
// resource: regr_4b
void SobelFilter::drive_global_state(){
  if ( (i_rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      global_state = global_state_next.read();
    }
  }
}
// resource: mux_4bx2i
void SobelFilter::drive_global_state_next(){
  switch( (sc_uint<4>)(global_state.read()) ) {
  default:
    global_state_next = (global_state.read() + 1ULL);
    break;
  case 0ULL: case 8ULL: 
    global_state_next = 1ULL;
    break;
  case 3ULL: 
    if ( SobelFilter_Lti3u2_4_32_out1.read() ) {
      global_state_next = 1ULL;
    } else {
      if ( SobelFilter_Lti3u2_4_31_out1.read() ) {
        global_state_next = 1ULL;
      } else {
        global_state_next = (global_state.read() + 1ULL);
      }
    }
    break;
  }
}
// resource: mux_1bx2i
// resource: regr_1b
void SobelFilter::drive_gs_ctrl0(){
  if ( (i_rst.read() == 0ULL) ) {
    gs_ctrl0 = 0ULL;
  } else {
    if ( stall0.read() );
    else {
      switch( (sc_uint<4>)(global_state_next.read()) ) {
      default:
        gs_ctrl0 = 0ULL;
        break;
      case 3ULL: 
        gs_ctrl0 = 1ULL;
        break;
      }
    }
  }
}
void SobelFilter::drive_i_rgb_busy(){
  i_rgb_busy = (sc_uint<1> ) (SobelFilter_And_1U_6_4_40_out1.read());
}
// resource: SobelFilter_Or_1U_9_4  instance: SobelFilter_Or_1U_9_4_39
void SobelFilter::SobelFilter_Or_1U_9_4_39(){
  SobelFilter_Or_1U_9_4_39_out1 = i_rgb_m_unvalidated_req.read() | i_rgb_vld
                                  .read();
}
// resource: SobelFilter_And_1U_6_4  instance: SobelFilter_And_1U_6_4_40
void SobelFilter::SobelFilter_And_1U_6_4_40(){
  SobelFilter_And_1U_6_4_40_out1 = (sc_uint<1> ) (SobelFilter_Or_1U_9_4_39_out1
                                   .read() & (sc_uint<1> )i_rgb_m_busy_req_0
                                   .read());
}
// resource: SobelFilter_Not_1U_1_4  instance: SobelFilter_Not_1U_1_4_41
void SobelFilter::SobelFilter_Not_1U_1_4_41(){
  SobelFilter_Not_1U_1_4_41_out1 = !SobelFilter_And_1U_6_4_40_out1.read();
}
// resource: SobelFilter_And_1U_6_4  instance: SobelFilter_And_1U_6_4_42
void SobelFilter::SobelFilter_And_1U_6_4_42(){
  SobelFilter_And_1U_6_4_42_out1 = (sc_uint<1> ) (SobelFilter_Not_1U_1_4_41_out1
                                   .read() & (sc_uint<1> )i_rgb_vld.read());
}
// resource: SobelFilter_Not_1U_1_4  instance: SobelFilter_Not_1U_1_4_43
void SobelFilter::SobelFilter_Not_1U_1_4_43(){
  SobelFilter_Not_1U_1_4_43_out1 = !SobelFilter_And_1U_6_4_42_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_i_rgb_m_unvalidated_req(){
  if ( (i_rst.read() == 0ULL) ) {
    i_rgb_m_unvalidated_req = 1ULL;
  } else {
    i_rgb_m_unvalidated_req = (sc_uint<1> ) (SobelFilter_N_Muxb_1_2_14_4_10_out1
                              .read());
  }
}
// resource: SobelFilter_N_Muxb_1_2_14_4
void SobelFilter::SobelFilter_N_Muxb_1_2_14_4_10(){
  if ( i_rgb_m_busy_req_0.read() ) {
    SobelFilter_N_Muxb_1_2_14_4_10_out1 = (sc_uint<1> ) (i_rgb_m_unvalidated_req
                                          .read());
  } else {
    SobelFilter_N_Muxb_1_2_14_4_10_out1 = (sc_uint<1> ) (i_rgb_vld.read());
  }
}
void SobelFilter::drive_o_newR_vld(){
  o_newR_vld = (sc_uint<1> ) (SobelFilter_Or_1U_9_4_2_out1.read());
}
// resource: SobelFilter_Or_1U_9_4  instance: SobelFilter_Or_1U_9_4_2
void SobelFilter::SobelFilter_Or_1U_9_4_2(){
  SobelFilter_Or_1U_9_4_2_out1 = o_newR_m_unacked_req.read() | (sc_uint<1>)
                                 SobelFilter_Xor_1U_11_4_1_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_o_newR_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newR_m_unacked_req = 0ULL;
  } else {
    o_newR_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1U_6_4_13_out1.read())
    ;
  }
}
// resource: SobelFilter_And_1U_6_4  instance: SobelFilter_And_1U_6_4_13
void SobelFilter::SobelFilter_And_1U_6_4_13(){
  SobelFilter_And_1U_6_4_13_out1 = (sc_uint<1> ) (o_newR_busy.read() & 
                                   o_newR_vld.read());
}
// resource: SobelFilter_Xor_1U_11_4  instance: SobelFilter_Xor_1U_11_4_1
void SobelFilter::SobelFilter_Xor_1U_11_4_1(){
  SobelFilter_Xor_1U_11_4_1_out1 = (sc_uint<1> ) (o_newR_m_req_m_trig_req.read()
                                    ^ o_newR_m_req_m_prev_trig_req.read());
}
// resource: regr_1b
void SobelFilter::drive_o_newR_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newR_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_newR_m_req_m_prev_trig_req = o_newR_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1_4  instance: SobelFilter_Not_1U_1_4_3
void SobelFilter::SobelFilter_Not_1U_1_4_3(){
  SobelFilter_Not_1U_1_4_3_out1 = !o_newR_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_newG_vld(){
  o_newG_vld = (sc_uint<1> ) (SobelFilter_Or_1U_9_4_5_out1.read());
}
// resource: SobelFilter_Or_1U_9_4  instance: SobelFilter_Or_1U_9_4_5
void SobelFilter::SobelFilter_Or_1U_9_4_5(){
  SobelFilter_Or_1U_9_4_5_out1 = o_newG_m_unacked_req.read() | (sc_uint<1>)
                                 SobelFilter_Xor_1U_11_4_4_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_o_newG_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newG_m_unacked_req = 0ULL;
  } else {
    o_newG_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1U_6_4_14_out1.read())
    ;
  }
}
// resource: SobelFilter_And_1U_6_4  instance: SobelFilter_And_1U_6_4_14
void SobelFilter::SobelFilter_And_1U_6_4_14(){
  SobelFilter_And_1U_6_4_14_out1 = (sc_uint<1> ) (o_newG_busy.read() & 
                                   o_newG_vld.read());
}
// resource: SobelFilter_Xor_1U_11_4  instance: SobelFilter_Xor_1U_11_4_4
void SobelFilter::SobelFilter_Xor_1U_11_4_4(){
  SobelFilter_Xor_1U_11_4_4_out1 = (sc_uint<1> ) (o_newG_m_req_m_trig_req.read()
                                    ^ o_newG_m_req_m_prev_trig_req.read());
}
// resource: regr_1b
void SobelFilter::drive_o_newG_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newG_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_newG_m_req_m_prev_trig_req = o_newG_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1_4  instance: SobelFilter_Not_1U_1_4_6
void SobelFilter::SobelFilter_Not_1U_1_4_6(){
  SobelFilter_Not_1U_1_4_6_out1 = !o_newG_m_req_m_trig_req.read();
}
void SobelFilter::drive_o_newB_vld(){
  o_newB_vld = (sc_uint<1> ) (SobelFilter_Or_1U_9_4_8_out1.read());
}
// resource: SobelFilter_Or_1U_9_4  instance: SobelFilter_Or_1U_9_4_8
void SobelFilter::SobelFilter_Or_1U_9_4_8(){
  SobelFilter_Or_1U_9_4_8_out1 = o_newB_m_unacked_req.read() | (sc_uint<1>)
                                 SobelFilter_Xor_1U_11_4_7_out1.read();
}
// resource: regr_1b
void SobelFilter::drive_o_newB_m_unacked_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newB_m_unacked_req = 0ULL;
  } else {
    o_newB_m_unacked_req = (sc_uint<1> ) (SobelFilter_And_1U_6_4_15_out1.read())
    ;
  }
}
// resource: SobelFilter_And_1U_6_4  instance: SobelFilter_And_1U_6_4_15
void SobelFilter::SobelFilter_And_1U_6_4_15(){
  SobelFilter_And_1U_6_4_15_out1 = (sc_uint<1> ) (o_newB_busy.read() & 
                                   o_newB_vld.read());
}
// resource: SobelFilter_Xor_1U_11_4  instance: SobelFilter_Xor_1U_11_4_7
void SobelFilter::SobelFilter_Xor_1U_11_4_7(){
  SobelFilter_Xor_1U_11_4_7_out1 = (sc_uint<1> ) (o_newB_m_req_m_trig_req.read()
                                    ^ o_newB_m_req_m_prev_trig_req.read());
}
// resource: regr_1b
void SobelFilter::drive_o_newB_m_req_m_prev_trig_req(){
  if ( (i_rst.read() == 0ULL) ) {
    o_newB_m_req_m_prev_trig_req = 0ULL;
  } else {
    o_newB_m_req_m_prev_trig_req = o_newB_m_req_m_trig_req.read();
  }
}
// resource: SobelFilter_Not_1U_1_4  instance: SobelFilter_Not_1U_1_4_9
void SobelFilter::SobelFilter_Not_1U_1_4_9(){
  SobelFilter_Not_1U_1_4_9_out1 = !o_newB_m_req_m_trig_req.read();
}
