`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 16 2019 23:11:54 CST (Nov 16 2019 15:11:54 UTC)

module SobelFilter_N_Mux_8_2_3_4(in2, ctrl1, out1);
  input [7:0] in2;
  input ctrl1;
  output [7:0] out1;
  wire [7:0] in2;
  wire ctrl1;
  wire [7:0] out1;
  NAND2BX1 g28(.AN (in2[0]), .B (ctrl1), .Y (out1[0]));
  NAND2BX1 g32(.AN (in2[1]), .B (ctrl1), .Y (out1[1]));
  NAND2BX1 g27(.AN (in2[7]), .B (ctrl1), .Y (out1[7]));
  NAND2BX1 g26(.AN (in2[6]), .B (ctrl1), .Y (out1[6]));
  NAND2BX1 g25(.AN (in2[4]), .B (ctrl1), .Y (out1[4]));
  NAND2BX1 g30(.AN (in2[5]), .B (ctrl1), .Y (out1[5]));
  NAND2BX1 g29(.AN (in2[2]), .B (ctrl1), .Y (out1[2]));
  NAND2BX1 g31(.AN (in2[3]), .B (ctrl1), .Y (out1[3]));
endmodule


