// Generated by stratus_hls 17.21-s100  (88813.070850)
// Sat Nov 16 23:15:37 2019
// from ../SobelFilter.cpp
#include "SobelFilter_ROM_9X8_embossFilterMask.h"

struct SobelFilter_ROM_9X8_embossFilterMask;
SobelFilter_ROM_9X8_embossFilterMask::SobelFilter_ROM_9X8_embossFilterMask(sc_module_name name) : sc_module(name) 
    ,in1("in1")
    ,out1("out1")
    ,clk("clk")
    ,embossFilterMask()
{
  CYN_ROM_INIT( sc_uint<8> , embossFilterMask, ENUMS::CYN_HEX, "bdw_work/modules/SobelFilter/BASIC/SobelFilter_ROM_9X8_embossFilterMask_0.memh", "initialize SobelFilter_ROM_9X8_embossFilterMask" ); 
  SC_METHOD(SobelFilter_ROM_9X8_embossFilterMask_thread_1);
  sensitive << clk.pos();
  dont_initialize();

}
void SobelFilter_ROM_9X8_embossFilterMask::SobelFilter_ROM_9X8_embossFilterMask_thread_1(){
  if ( (/*imp*/sc_uint<1>)(in1.read() < ((/*imp*/sc_uint<4> )(9ULL))) ) {
    out1 = (sc_uint<8> ) ((embossFilterMask)[in1.read()]);
  } 
}
