`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2019 10:14:22 CST (Nov 17 2019 02:14:22 UTC)

module SobelFilter_Add2i128s32_1(in1, out1);
  input [31:0] in1;
  output [31:0] out1;
  wire [31:0] in1;
  wire [31:0] out1;
  wire add_33_2_n_4, add_33_2_n_5, add_33_2_n_6, add_33_2_n_7,
       add_33_2_n_10, add_33_2_n_11, add_33_2_n_12, add_33_2_n_13;
  wire add_33_2_n_14, add_33_2_n_15, add_33_2_n_16, add_33_2_n_17,
       add_33_2_n_18, add_33_2_n_19, add_33_2_n_20, add_33_2_n_21;
  wire add_33_2_n_22, add_33_2_n_23, add_33_2_n_24, add_33_2_n_25,
       add_33_2_n_26, add_33_2_n_27, add_33_2_n_28, add_33_2_n_29;
  wire add_33_2_n_30, add_33_2_n_31, add_33_2_n_32, add_33_2_n_33,
       add_33_2_n_34, add_33_2_n_35, add_33_2_n_36, add_33_2_n_37;
  wire add_33_2_n_38, add_33_2_n_39, add_33_2_n_40, add_33_2_n_41,
       add_33_2_n_42, add_33_2_n_43, add_33_2_n_44, add_33_2_n_45;
  wire add_33_2_n_46, add_33_2_n_48, add_33_2_n_49, add_33_2_n_51,
       add_33_2_n_52, add_33_2_n_53, add_33_2_n_54, add_33_2_n_55;
  wire add_33_2_n_56, add_33_2_n_57, add_33_2_n_58, add_33_2_n_59,
       add_33_2_n_60, add_33_2_n_61, add_33_2_n_62, add_33_2_n_63;
  wire add_33_2_n_64, add_33_2_n_65, add_33_2_n_66, add_33_2_n_67,
       add_33_2_n_68, add_33_2_n_69, add_33_2_n_70, add_33_2_n_71;
  wire add_33_2_n_72, add_33_2_n_73, add_33_2_n_74, add_33_2_n_75,
       add_33_2_n_76, add_33_2_n_77, add_33_2_n_78, add_33_2_n_79;
  wire add_33_2_n_80, add_33_2_n_81, add_33_2_n_82, add_33_2_n_83,
       add_33_2_n_85, add_33_2_n_86, add_33_2_n_87, add_33_2_n_88;
  wire add_33_2_n_89, add_33_2_n_90, add_33_2_n_91, add_33_2_n_152,
       add_33_2_n_153, add_33_2_n_154;
  assign out1[0] = in1[0];
  assign out1[1] = in1[1];
  assign out1[2] = in1[2];
  assign out1[3] = in1[3];
  assign out1[4] = in1[4];
  assign out1[5] = in1[5];
  assign out1[6] = in1[6];
  INVX1 g7(.A (in1[7]), .Y (out1[7]));
  MXI2XL add_33_2_g725(.A (add_33_2_n_16), .B (in1[17]), .S0
       (add_33_2_n_90), .Y (out1[17]));
  MXI2XL add_33_2_g726(.A (add_33_2_n_12), .B (in1[22]), .S0
       (add_33_2_n_83), .Y (out1[22]));
  MXI2XL add_33_2_g727(.A (add_33_2_n_17), .B (in1[21]), .S0
       (add_33_2_n_87), .Y (out1[21]));
  MXI2XL add_33_2_g728(.A (add_33_2_n_18), .B (in1[25]), .S0
       (add_33_2_n_86), .Y (out1[25]));
  MXI2XL add_33_2_g729(.A (add_33_2_n_26), .B (in1[23]), .S0
       (add_33_2_n_77), .Y (out1[23]));
  MXI2XL add_33_2_g730(.A (add_33_2_n_19), .B (in1[29]), .S0
       (add_33_2_n_81), .Y (out1[29]));
  MXI2XL add_33_2_g731(.A (add_33_2_n_24), .B (in1[27]), .S0
       (add_33_2_n_82), .Y (out1[27]));
  MXI2XL add_33_2_g732(.A (add_33_2_n_25), .B (in1[19]), .S0
       (add_33_2_n_80), .Y (out1[19]));
  MXI2XL add_33_2_g733(.A (add_33_2_n_27), .B (in1[30]), .S0
       (add_33_2_n_79), .Y (out1[30]));
  MXI2XL add_33_2_g734(.A (add_33_2_n_11), .B (in1[28]), .S0
       (add_33_2_n_85), .Y (out1[28]));
  MXI2XL add_33_2_g735(.A (add_33_2_n_23), .B (in1[26]), .S0
       (add_33_2_n_78), .Y (out1[26]));
  MXI2XL add_33_2_g736(.A (add_33_2_n_22), .B (in1[24]), .S0
       (add_33_2_n_7), .Y (out1[24]));
  MXI2XL add_33_2_g737(.A (add_33_2_n_29), .B (in1[31]), .S0
       (add_33_2_n_91), .Y (out1[31]));
  MXI2XL add_33_2_g738(.A (add_33_2_n_14), .B (in1[18]), .S0
       (add_33_2_n_88), .Y (out1[18]));
  MXI2XL add_33_2_g739(.A (add_33_2_n_21), .B (in1[20]), .S0
       (add_33_2_n_89), .Y (out1[20]));
  MXI2XL add_33_2_g741(.A (add_33_2_n_28), .B (in1[15]), .S0
       (add_33_2_n_67), .Y (out1[15]));
  MXI2XL add_33_2_g742(.A (add_33_2_n_13), .B (in1[14]), .S0
       (add_33_2_n_72), .Y (out1[14]));
  NOR2X1 add_33_2_g744(.A (add_33_2_n_76), .B (add_33_2_n_69), .Y
       (add_33_2_n_91));
  NOR2XL add_33_2_g745(.A (add_33_2_n_15), .B (add_33_2_n_76), .Y
       (add_33_2_n_90));
  NOR2XL add_33_2_g747(.A (add_33_2_n_48), .B (add_33_2_n_76), .Y
       (add_33_2_n_89));
  NOR2XL add_33_2_g748(.A (add_33_2_n_36), .B (add_33_2_n_76), .Y
       (add_33_2_n_88));
  NOR2XL add_33_2_g749(.A (add_33_2_n_66), .B (add_33_2_n_76), .Y
       (add_33_2_n_87));
  NOR2X1 add_33_2_g750(.A (add_33_2_n_74), .B (add_33_2_n_76), .Y
       (add_33_2_n_86));
  NOR2XL add_33_2_g751(.A (add_33_2_n_76), .B (add_33_2_n_6), .Y
       (add_33_2_n_85));
  MXI2XL add_33_2_g752(.A (in1[12]), .B (add_33_2_n_10), .S0
       (add_33_2_n_63), .Y (out1[12]));
  NOR2XL add_33_2_g754(.A (add_33_2_n_65), .B (add_33_2_n_76), .Y
       (add_33_2_n_83));
  NOR2XL add_33_2_g755(.A (add_33_2_n_76), .B (add_33_2_n_71), .Y
       (add_33_2_n_82));
  NOR2XL add_33_2_g756(.A (add_33_2_n_76), .B (add_33_2_n_70), .Y
       (add_33_2_n_81));
  NOR2XL add_33_2_g757(.A (add_33_2_n_56), .B (add_33_2_n_76), .Y
       (add_33_2_n_80));
  NOR2XL add_33_2_g758(.A (add_33_2_n_76), .B (add_33_2_n_73), .Y
       (add_33_2_n_79));
  NOR2XL add_33_2_g759(.A (add_33_2_n_76), .B (add_33_2_n_75), .Y
       (add_33_2_n_78));
  NOR2XL add_33_2_g760(.A (add_33_2_n_61), .B (add_33_2_n_76), .Y
       (add_33_2_n_77));
  NAND2X1 add_33_2_g762(.A (add_33_2_n_35), .B (add_33_2_n_62), .Y
       (add_33_2_n_75));
  NAND2X1 add_33_2_g764(.A (in1[24]), .B (add_33_2_n_62), .Y
       (add_33_2_n_74));
  NAND2X1 add_33_2_g765(.A (add_33_2_n_62), .B (add_33_2_n_5), .Y
       (add_33_2_n_73));
  NOR3X1 add_33_2_g766(.A (add_33_2_n_20), .B (add_33_2_n_41), .C
       (add_33_2_n_152), .Y (add_33_2_n_72));
  NAND2X8 add_33_2_g767(.A (in1[7]), .B (add_33_2_n_60), .Y
       (add_33_2_n_76));
  NAND2X1 add_33_2_g769(.A (add_33_2_n_4), .B (add_33_2_n_62), .Y
       (add_33_2_n_71));
  NAND2X1 add_33_2_g770(.A (add_33_2_n_62), .B (add_33_2_n_64), .Y
       (add_33_2_n_70));
  NAND2X1 add_33_2_g772(.A (add_33_2_n_62), .B (add_33_2_n_58), .Y
       (add_33_2_n_69));
  NOR3X1 add_33_2_g773(.A (add_33_2_n_20), .B (add_33_2_n_10), .C
       (add_33_2_n_154), .Y (add_33_2_n_68));
  NOR2X1 add_33_2_g774(.A (add_33_2_n_20), .B (add_33_2_n_59), .Y
       (add_33_2_n_67));
  NAND2X1 add_33_2_g775(.A (in1[20]), .B (add_33_2_n_49), .Y
       (add_33_2_n_66));
  OR2XL add_33_2_g776(.A (add_33_2_n_40), .B (add_33_2_n_48), .Y
       (add_33_2_n_65));
  NOR2X1 add_33_2_g778(.A (add_33_2_n_11), .B (add_33_2_n_52), .Y
       (add_33_2_n_64));
  NAND2X1 add_33_2_g779(.A (in1[7]), .B (add_33_2_n_153), .Y
       (add_33_2_n_63));
  NAND2X1 add_33_2_g781(.A (add_33_2_n_55), .B (add_33_2_n_49), .Y
       (add_33_2_n_61));
  CLKAND2X6 add_33_2_g782(.A (add_33_2_n_45), .B (add_33_2_n_51), .Y
       (add_33_2_n_60));
  NAND2X1 add_33_2_g783(.A (add_33_2_n_57), .B (add_33_2_n_153), .Y
       (add_33_2_n_59));
  NOR2X1 add_33_2_g784(.A (add_33_2_n_54), .B (add_33_2_n_52), .Y
       (add_33_2_n_58));
  CLKAND2X3 add_33_2_g785(.A (add_33_2_n_46), .B (add_33_2_n_49), .Y
       (add_33_2_n_62));
  NOR2X1 add_33_2_g786(.A (add_33_2_n_13), .B (add_33_2_n_41), .Y
       (add_33_2_n_57));
  OR2XL add_33_2_g787(.A (add_33_2_n_14), .B (add_33_2_n_36), .Y
       (add_33_2_n_56));
  NOR2X1 add_33_2_g789(.A (add_33_2_n_12), .B (add_33_2_n_40), .Y
       (add_33_2_n_55));
  NAND2X1 add_33_2_g790(.A (in1[30]), .B (add_33_2_n_43), .Y
       (add_33_2_n_54));
  NOR2X1 add_33_2_g791(.A (add_33_2_n_20), .B (add_33_2_n_42), .Y
       (add_33_2_n_53));
  INVX1 add_33_2_g794(.A (add_33_2_n_49), .Y (add_33_2_n_48));
  MXI2XL add_33_2_g795(.A (add_33_2_n_20), .B (in1[7]), .S0 (in1[8]),
       .Y (out1[8]));
  NOR2X1 add_33_2_g796(.A (add_33_2_n_31), .B (add_33_2_n_40), .Y
       (add_33_2_n_46));
  NOR2X4 add_33_2_g797(.A (add_33_2_n_37), .B (add_33_2_n_41), .Y
       (add_33_2_n_45));
  NOR2X1 add_33_2_g798(.A (add_33_2_n_42), .B (add_33_2_n_32), .Y
       (add_33_2_n_44));
  NAND2X2 add_33_2_g799(.A (add_33_2_n_39), .B (add_33_2_n_35), .Y
       (add_33_2_n_52));
  NOR2X6 add_33_2_g800(.A (add_33_2_n_34), .B (add_33_2_n_38), .Y
       (add_33_2_n_51));
  NOR2X4 add_33_2_g801(.A (add_33_2_n_33), .B (add_33_2_n_36), .Y
       (add_33_2_n_49));
  NOR2X2 add_33_2_g803(.A (add_33_2_n_24), .B (add_33_2_n_23), .Y
       (add_33_2_n_39));
  NAND2X4 add_33_2_g804(.A (in1[9]), .B (in1[8]), .Y (add_33_2_n_38));
  NAND2X8 add_33_2_g805(.A (in1[15]), .B (in1[14]), .Y (add_33_2_n_37));
  NOR2X1 add_33_2_g806(.A (add_33_2_n_19), .B (add_33_2_n_11), .Y
       (add_33_2_n_43));
  NAND2X2 add_33_2_g807(.A (in1[9]), .B (in1[8]), .Y (add_33_2_n_42));
  NAND2X6 add_33_2_g808(.A (in1[13]), .B (in1[12]), .Y (add_33_2_n_41));
  NAND2X4 add_33_2_g809(.A (in1[21]), .B (in1[20]), .Y (add_33_2_n_40));
  NAND2X8 add_33_2_g811(.A (in1[11]), .B (in1[10]), .Y (add_33_2_n_34));
  NAND2X4 add_33_2_g812(.A (in1[19]), .B (in1[18]), .Y (add_33_2_n_33));
  NAND2X1 add_33_2_g813(.A (in1[10]), .B (in1[7]), .Y (add_33_2_n_32));
  NAND2X2 add_33_2_g814(.A (in1[23]), .B (in1[22]), .Y (add_33_2_n_31));
  NAND2X1 add_33_2_g815(.A (in1[8]), .B (in1[7]), .Y (add_33_2_n_30));
  NAND2X4 add_33_2_g816(.A (in1[17]), .B (in1[16]), .Y (add_33_2_n_36));
  NOR2X2 add_33_2_g817(.A (add_33_2_n_18), .B (add_33_2_n_22), .Y
       (add_33_2_n_35));
  INVXL add_33_2_g818(.A (in1[31]), .Y (add_33_2_n_29));
  INVXL add_33_2_g819(.A (in1[15]), .Y (add_33_2_n_28));
  INVXL add_33_2_g820(.A (in1[30]), .Y (add_33_2_n_27));
  INVXL add_33_2_g821(.A (in1[23]), .Y (add_33_2_n_26));
  INVXL add_33_2_g822(.A (in1[19]), .Y (add_33_2_n_25));
  CLKINVX2 add_33_2_g824(.A (in1[27]), .Y (add_33_2_n_24));
  CLKINVX2 add_33_2_g825(.A (in1[26]), .Y (add_33_2_n_23));
  CLKINVX2 add_33_2_g826(.A (in1[24]), .Y (add_33_2_n_22));
  INVXL add_33_2_g827(.A (in1[20]), .Y (add_33_2_n_21));
  INVX1 add_33_2_g829(.A (in1[7]), .Y (add_33_2_n_20));
  INVX1 add_33_2_g830(.A (in1[29]), .Y (add_33_2_n_19));
  CLKINVX2 add_33_2_g831(.A (in1[25]), .Y (add_33_2_n_18));
  INVXL add_33_2_g833(.A (in1[21]), .Y (add_33_2_n_17));
  INVXL add_33_2_g834(.A (in1[17]), .Y (add_33_2_n_16));
  INVX1 add_33_2_g835(.A (in1[16]), .Y (add_33_2_n_15));
  INVX1 add_33_2_g836(.A (in1[18]), .Y (add_33_2_n_14));
  INVX1 add_33_2_g837(.A (in1[14]), .Y (add_33_2_n_13));
  INVX1 add_33_2_g838(.A (in1[22]), .Y (add_33_2_n_12));
  INVX1 add_33_2_g840(.A (in1[28]), .Y (add_33_2_n_11));
  INVX1 add_33_2_g841(.A (in1[12]), .Y (add_33_2_n_10));
  MXI2XL add_33_2_g2(.A (in1[16]), .B (add_33_2_n_15), .S0
       (add_33_2_n_76), .Y (out1[16]));
  NOR2BX1 add_33_2_g844(.AN (add_33_2_n_62), .B (add_33_2_n_76), .Y
       (add_33_2_n_7));
  NAND2BX1 add_33_2_g845(.AN (add_33_2_n_52), .B (add_33_2_n_62), .Y
       (add_33_2_n_6));
  NOR2BX1 add_33_2_g846(.AN (add_33_2_n_43), .B (add_33_2_n_52), .Y
       (add_33_2_n_5));
  NOR2BX1 add_33_2_g847(.AN (add_33_2_n_35), .B (add_33_2_n_23), .Y
       (add_33_2_n_4));
  XOR2XL add_33_2_g848(.A (in1[13]), .B (add_33_2_n_68), .Y (out1[13]));
  XNOR2X1 add_33_2_g849(.A (in1[9]), .B (add_33_2_n_30), .Y (out1[9]));
  CLKXOR2X1 add_33_2_g850(.A (in1[11]), .B (add_33_2_n_44), .Y
       (out1[11]));
  CLKXOR2X1 add_33_2_g851(.A (in1[10]), .B (add_33_2_n_53), .Y
       (out1[10]));
  CLKINVX1 add_33_2_fopt(.A (add_33_2_n_153), .Y (add_33_2_n_152));
  CLKINVX2 add_33_2_fopt852(.A (add_33_2_n_154), .Y (add_33_2_n_153));
  CLKINVX1 add_33_2_fopt853(.A (add_33_2_n_51), .Y (add_33_2_n_154));
endmodule


