`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 17 2019 10:14:07 CST (Nov 17 2019 02:14:07 UTC)

module SobelFilter_Lti255s32_4(in1, out1);
  input [31:0] in1;
  output out1;
  wire [31:0] in1;
  wire out1;
  wire gt_31_105_n_0, gt_31_105_n_1, gt_31_105_n_2, gt_31_105_n_3,
       gt_31_105_n_4, gt_31_105_n_5, gt_31_105_n_6, gt_31_105_n_7;
  wire gt_31_105_n_8, gt_31_105_n_9, gt_31_105_n_10, gt_31_105_n_11;
  NAND2BX1 gt_31_105_g581(.AN (in1[31]), .B (gt_31_105_n_11), .Y
       (out1));
  NAND4XL gt_31_105_g582(.A (gt_31_105_n_6), .B (gt_31_105_n_3), .C
       (gt_31_105_n_5), .D (gt_31_105_n_10), .Y (gt_31_105_n_11));
  NOR4X1 gt_31_105_g583(.A (gt_31_105_n_2), .B (gt_31_105_n_9), .C
       (in1[13]), .D (in1[12]), .Y (gt_31_105_n_10));
  OAI211X1 gt_31_105_g584(.A0 (gt_31_105_n_0), .A1 (gt_31_105_n_8), .B0
       (gt_31_105_n_1), .C0 (gt_31_105_n_4), .Y (gt_31_105_n_9));
  NAND3BXL gt_31_105_g585(.AN (gt_31_105_n_7), .B (in1[1]), .C
       (in1[3]), .Y (gt_31_105_n_8));
  NAND4XL gt_31_105_g586(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D
       (in1[4]), .Y (gt_31_105_n_7));
  NOR4X1 gt_31_105_g587(.A (in1[27]), .B (in1[26]), .C (in1[25]), .D
       (in1[24]), .Y (gt_31_105_n_6));
  NOR4X1 gt_31_105_g588(.A (in1[31]), .B (in1[30]), .C (in1[29]), .D
       (in1[28]), .Y (gt_31_105_n_5));
  NOR4X1 gt_31_105_g589(.A (in1[11]), .B (in1[10]), .C (in1[9]), .D
       (in1[8]), .Y (gt_31_105_n_4));
  NOR4X1 gt_31_105_g590(.A (in1[23]), .B (in1[22]), .C (in1[21]), .D
       (in1[20]), .Y (gt_31_105_n_3));
  OR4X1 gt_31_105_g591(.A (in1[19]), .B (in1[18]), .C (in1[17]), .D
       (in1[16]), .Y (gt_31_105_n_2));
  NOR2X1 gt_31_105_g592(.A (in1[15]), .B (in1[14]), .Y (gt_31_105_n_1));
  NAND2X1 gt_31_105_g593(.A (in1[2]), .B (in1[0]), .Y (gt_31_105_n_0));
endmodule


