`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 16 2019 23:12:06 CST (Nov 16 2019 15:12:06 UTC)

module SobelFilter_Not_1U_1U_1(in1, out1);
  input in1;
  output out1;
  wire in1;
  wire out1;
  CLKINVX12 g2(.A (in1), .Y (out1));
endmodule


