`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 16 2019 23:11:53 CST (Nov 16 2019 15:11:53 UTC)

module SobelFilter_And_1Ux1U_1U_4(in2, in1, out1);
  input in2, in1;
  output out1;
  wire in2, in1;
  wire out1;
  AND2XL g8(.A (in2), .B (in1), .Y (out1));
endmodule


