// Generated by stratus_hls 17.21-s100  (88813.070850)
// Sun Nov 17 10:14:34 2019
// from ../SobelFilter.cpp
#ifndef CYNTH_PART_SobelFilter_SobelFilter_ROM_9X8_embossFilterMask_h
#define CYNTH_PART_SobelFilter_SobelFilter_ROM_9X8_embossFilterMask_h

#include "systemc.h"
#include "cynthhl.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct SobelFilter_ROM_9X8_embossFilterMask : public sc_module {
  sc_in<sc_uint<4> > in1;
  sc_out<sc_uint<8> > out1;
  sc_in<bool > clk;
  SobelFilter_ROM_9X8_embossFilterMask( sc_module_name name );
  SC_HAS_PROCESS(SobelFilter_ROM_9X8_embossFilterMask);
  /*const*/ sc_uint<8> embossFilterMask[9];
  void SobelFilter_ROM_9X8_embossFilterMask_thread_1();
};

#endif
