`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 16 2019 23:15:24 CST (Nov 16 2019 15:15:24 UTC)

module SobelFilter_Mul_8Sx8U_16S_4(in2, in1, out1);
  input [7:0] in2, in1;
  output [15:0] out1;
  wire [7:0] in2, in1;
  wire [15:0] out1;
  wire mul_34_8_n_0, mul_34_8_n_1, mul_34_8_n_2, mul_34_8_n_3,
       mul_34_8_n_4, mul_34_8_n_5, mul_34_8_n_6, mul_34_8_n_7;
  wire mul_34_8_n_8, mul_34_8_n_9, mul_34_8_n_10, mul_34_8_n_11,
       mul_34_8_n_12, mul_34_8_n_13, mul_34_8_n_14, mul_34_8_n_15;
  wire mul_34_8_n_17, mul_34_8_n_18, mul_34_8_n_19, mul_34_8_n_20,
       mul_34_8_n_21, mul_34_8_n_22, mul_34_8_n_23, mul_34_8_n_24;
  wire mul_34_8_n_25, mul_34_8_n_26, mul_34_8_n_27, mul_34_8_n_28,
       mul_34_8_n_29, mul_34_8_n_30, mul_34_8_n_31, mul_34_8_n_32;
  wire mul_34_8_n_33, mul_34_8_n_34, mul_34_8_n_35, mul_34_8_n_36,
       mul_34_8_n_37, mul_34_8_n_38, mul_34_8_n_39, mul_34_8_n_40;
  wire mul_34_8_n_41, mul_34_8_n_42, mul_34_8_n_43, mul_34_8_n_44,
       mul_34_8_n_45, mul_34_8_n_46, mul_34_8_n_47, mul_34_8_n_48;
  wire mul_34_8_n_49, mul_34_8_n_50, mul_34_8_n_51, mul_34_8_n_52,
       mul_34_8_n_53, mul_34_8_n_54, mul_34_8_n_55, mul_34_8_n_56;
  wire mul_34_8_n_57, mul_34_8_n_58, mul_34_8_n_59, mul_34_8_n_60,
       mul_34_8_n_61, mul_34_8_n_62, mul_34_8_n_63, mul_34_8_n_64;
  wire mul_34_8_n_65, mul_34_8_n_66, mul_34_8_n_67, mul_34_8_n_68,
       mul_34_8_n_69, mul_34_8_n_70, mul_34_8_n_71, mul_34_8_n_72;
  wire mul_34_8_n_73, mul_34_8_n_74, mul_34_8_n_75, mul_34_8_n_76,
       mul_34_8_n_77, mul_34_8_n_78, mul_34_8_n_79, mul_34_8_n_80;
  wire mul_34_8_n_81, mul_34_8_n_82, mul_34_8_n_83, mul_34_8_n_84,
       mul_34_8_n_85, mul_34_8_n_86, mul_34_8_n_87, mul_34_8_n_88;
  wire mul_34_8_n_89, mul_34_8_n_90, mul_34_8_n_91, mul_34_8_n_92,
       mul_34_8_n_93, mul_34_8_n_94, mul_34_8_n_95, mul_34_8_n_96;
  wire mul_34_8_n_97, mul_34_8_n_98, mul_34_8_n_99, mul_34_8_n_100,
       mul_34_8_n_101, mul_34_8_n_102, mul_34_8_n_103, mul_34_8_n_104;
  wire mul_34_8_n_105, mul_34_8_n_106, mul_34_8_n_107, mul_34_8_n_108,
       mul_34_8_n_109, mul_34_8_n_110, mul_34_8_n_111, mul_34_8_n_112;
  wire mul_34_8_n_113, mul_34_8_n_114, mul_34_8_n_115, mul_34_8_n_116,
       mul_34_8_n_117, mul_34_8_n_118, mul_34_8_n_119, mul_34_8_n_120;
  wire mul_34_8_n_121, mul_34_8_n_122, mul_34_8_n_123, mul_34_8_n_124,
       mul_34_8_n_125, mul_34_8_n_127, mul_34_8_n_128, mul_34_8_n_129;
  wire mul_34_8_n_130, mul_34_8_n_131, mul_34_8_n_132, mul_34_8_n_133,
       mul_34_8_n_134, mul_34_8_n_135, mul_34_8_n_136, mul_34_8_n_137;
  wire mul_34_8_n_138, mul_34_8_n_139, mul_34_8_n_140, mul_34_8_n_141,
       mul_34_8_n_142, mul_34_8_n_143, mul_34_8_n_144, mul_34_8_n_145;
  wire mul_34_8_n_146, mul_34_8_n_147, mul_34_8_n_149, mul_34_8_n_150,
       mul_34_8_n_151, mul_34_8_n_152, mul_34_8_n_153, mul_34_8_n_154;
  wire mul_34_8_n_155, mul_34_8_n_156, mul_34_8_n_157, mul_34_8_n_158,
       mul_34_8_n_159, mul_34_8_n_160, mul_34_8_n_161, mul_34_8_n_162;
  wire mul_34_8_n_163, mul_34_8_n_164, mul_34_8_n_165, mul_34_8_n_167,
       mul_34_8_n_168, mul_34_8_n_169, mul_34_8_n_170, mul_34_8_n_171;
  wire mul_34_8_n_172, mul_34_8_n_173, mul_34_8_n_174, mul_34_8_n_175,
       mul_34_8_n_176, mul_34_8_n_178, mul_34_8_n_179, mul_34_8_n_180;
  wire mul_34_8_n_181, mul_34_8_n_182, mul_34_8_n_183, mul_34_8_n_184,
       mul_34_8_n_185, mul_34_8_n_186, mul_34_8_n_187, mul_34_8_n_188;
  wire mul_34_8_n_189, mul_34_8_n_190, mul_34_8_n_191, mul_34_8_n_192,
       mul_34_8_n_193, mul_34_8_n_194, mul_34_8_n_195, mul_34_8_n_196;
  wire mul_34_8_n_198, mul_34_8_n_199, mul_34_8_n_200, mul_34_8_n_201,
       mul_34_8_n_202, mul_34_8_n_203, mul_34_8_n_205, mul_34_8_n_206;
  wire mul_34_8_n_207, mul_34_8_n_208, mul_34_8_n_210, mul_34_8_n_211,
       mul_34_8_n_212, mul_34_8_n_214, mul_34_8_n_215, mul_34_8_n_216;
  wire mul_34_8_n_219, mul_34_8_n_220, mul_34_8_n_222, mul_34_8_n_224,
       mul_34_8_n_226;
  XNOR2X1 mul_34_8_g2222(.A (mul_34_8_n_125), .B (mul_34_8_n_226), .Y
       (out1[15]));
  ADDFX1 mul_34_8_g2223(.A (mul_34_8_n_224), .B (mul_34_8_n_121), .CI
       (mul_34_8_n_141), .CO (mul_34_8_n_226), .S (out1[14]));
  ADDFX1 mul_34_8_g2224(.A (mul_34_8_n_222), .B (mul_34_8_n_142), .CI
       (mul_34_8_n_160), .CO (mul_34_8_n_224), .S (out1[13]));
  ADDFX1 mul_34_8_g2225(.A (mul_34_8_n_219), .B (mul_34_8_n_175), .CI
       (mul_34_8_n_161), .CO (mul_34_8_n_222), .S (out1[12]));
  XNOR2X1 mul_34_8_g2226(.A (mul_34_8_n_196), .B (mul_34_8_n_220), .Y
       (out1[11]));
  OAI21X1 mul_34_8_g2227(.A0 (mul_34_8_n_195), .A1 (mul_34_8_n_216),
       .B0 (mul_34_8_n_189), .Y (mul_34_8_n_220));
  OAI211X1 mul_34_8_g2228(.A0 (mul_34_8_n_203), .A1 (mul_34_8_n_214),
       .B0 (mul_34_8_n_210), .C0 (mul_34_8_n_179), .Y (mul_34_8_n_219));
  XNOR2X1 mul_34_8_g2229(.A (mul_34_8_n_202), .B (mul_34_8_n_216), .Y
       (out1[10]));
  XNOR2X1 mul_34_8_g2230(.A (mul_34_8_n_201), .B (mul_34_8_n_215), .Y
       (out1[9]));
  NOR2BX1 mul_34_8_g2231(.AN (mul_34_8_n_214), .B (mul_34_8_n_207), .Y
       (mul_34_8_n_216));
  NOR2BX1 mul_34_8_g2232(.AN (mul_34_8_n_192), .B (mul_34_8_n_212), .Y
       (mul_34_8_n_215));
  NAND2BX1 mul_34_8_g2233(.AN (mul_34_8_n_191), .B (mul_34_8_n_212), .Y
       (mul_34_8_n_214));
  XNOR2X1 mul_34_8_g2234(.A (mul_34_8_n_199), .B (mul_34_8_n_211), .Y
       (out1[8]));
  NOR2X1 mul_34_8_g2235(.A (mul_34_8_n_190), .B (mul_34_8_n_211), .Y
       (mul_34_8_n_212));
  AOI221X1 mul_34_8_g2236(.A0 (mul_34_8_n_163), .A1 (mul_34_8_n_198),
       .B0 (mul_34_8_n_178), .B1 (mul_34_8_n_198), .C0
       (mul_34_8_n_205), .Y (mul_34_8_n_211));
  OA22X1 mul_34_8_g2237(.A0 (mul_34_8_n_203), .A1 (mul_34_8_n_208), .B0
       (mul_34_8_n_180), .B1 (mul_34_8_n_189), .Y (mul_34_8_n_210));
  XNOR2X1 mul_34_8_g2238(.A (mul_34_8_n_200), .B (mul_34_8_n_206), .Y
       (out1[7]));
  INVXL mul_34_8_g2239(.A (mul_34_8_n_207), .Y (mul_34_8_n_208));
  OAI21X1 mul_34_8_g2240(.A0 (mul_34_8_n_192), .A1 (mul_34_8_n_191),
       .B0 (mul_34_8_n_194), .Y (mul_34_8_n_207));
  OAI21X1 mul_34_8_g2241(.A0 (mul_34_8_n_169), .A1 (mul_34_8_n_193),
       .B0 (mul_34_8_n_168), .Y (mul_34_8_n_206));
  OAI21X1 mul_34_8_g2242(.A0 (mul_34_8_n_168), .A1 (mul_34_8_n_188),
       .B0 (mul_34_8_n_187), .Y (mul_34_8_n_205));
  XNOR2X1 mul_34_8_g2243(.A (mul_34_8_n_182), .B (mul_34_8_n_193), .Y
       (out1[6]));
  OR2XL mul_34_8_g2244(.A (mul_34_8_n_180), .B (mul_34_8_n_195), .Y
       (mul_34_8_n_203));
  NOR2BX1 mul_34_8_g2245(.AN (mul_34_8_n_189), .B (mul_34_8_n_195), .Y
       (mul_34_8_n_202));
  NOR2BX1 mul_34_8_g2246(.AN (mul_34_8_n_194), .B (mul_34_8_n_191), .Y
       (mul_34_8_n_201));
  NAND2BX1 mul_34_8_g2247(.AN (mul_34_8_n_188), .B (mul_34_8_n_187), .Y
       (mul_34_8_n_200));
  NOR2BX1 mul_34_8_g2248(.AN (mul_34_8_n_192), .B (mul_34_8_n_190), .Y
       (mul_34_8_n_199));
  NOR2X1 mul_34_8_g2249(.A (mul_34_8_n_169), .B (mul_34_8_n_188), .Y
       (mul_34_8_n_198));
  XNOR2X1 mul_34_8_g2250(.A (mul_34_8_n_162), .B (mul_34_8_n_181), .Y
       (out1[5]));
  NAND2BX1 mul_34_8_g2251(.AN (mul_34_8_n_180), .B (mul_34_8_n_179), .Y
       (mul_34_8_n_196));
  NOR2X1 mul_34_8_g2252(.A (mul_34_8_n_185), .B (mul_34_8_n_172), .Y
       (mul_34_8_n_195));
  NAND2XL mul_34_8_g2253(.A (mul_34_8_n_173), .B (mul_34_8_n_186), .Y
       (mul_34_8_n_194));
  NOR2X1 mul_34_8_g2254(.A (mul_34_8_n_178), .B (mul_34_8_n_163), .Y
       (mul_34_8_n_193));
  NAND2X1 mul_34_8_g2255(.A (mul_34_8_n_183), .B (mul_34_8_n_174), .Y
       (mul_34_8_n_192));
  NOR2X1 mul_34_8_g2256(.A (mul_34_8_n_173), .B (mul_34_8_n_186), .Y
       (mul_34_8_n_191));
  NOR2X1 mul_34_8_g2257(.A (mul_34_8_n_183), .B (mul_34_8_n_174), .Y
       (mul_34_8_n_190));
  NAND2XL mul_34_8_g2258(.A (mul_34_8_n_185), .B (mul_34_8_n_172), .Y
       (mul_34_8_n_189));
  NOR2X1 mul_34_8_g2259(.A (mul_34_8_n_164), .B (mul_34_8_n_184), .Y
       (mul_34_8_n_188));
  NAND2X1 mul_34_8_g2260(.A (mul_34_8_n_164), .B (mul_34_8_n_184), .Y
       (mul_34_8_n_187));
  ADDFX1 mul_34_8_g2261(.A (mul_34_8_n_150), .B (mul_34_8_n_153), .CI
       (mul_34_8_n_123), .CO (mul_34_8_n_185), .S (mul_34_8_n_186));
  ADDFX1 mul_34_8_g2262(.A (mul_34_8_n_151), .B (mul_34_8_n_128), .CI
       (mul_34_8_n_136), .CO (mul_34_8_n_183), .S (mul_34_8_n_184));
  NOR2BX1 mul_34_8_g2263(.AN (mul_34_8_n_168), .B (mul_34_8_n_169), .Y
       (mul_34_8_n_182));
  NAND2X1 mul_34_8_g2264(.A (mul_34_8_n_145), .B (mul_34_8_n_170), .Y
       (mul_34_8_n_181));
  NOR2X1 mul_34_8_g2265(.A (mul_34_8_n_171), .B (mul_34_8_n_176), .Y
       (mul_34_8_n_180));
  NAND2X1 mul_34_8_g2266(.A (mul_34_8_n_171), .B (mul_34_8_n_176), .Y
       (mul_34_8_n_179));
  NOR2X1 mul_34_8_g2267(.A (mul_34_8_n_159), .B (mul_34_8_n_170), .Y
       (mul_34_8_n_178));
  XNOR2X1 mul_34_8_g2268(.A (mul_34_8_n_167), .B (mul_34_8_n_158), .Y
       (out1[4]));
  ADDFX1 mul_34_8_g2269(.A (mul_34_8_n_143), .B (mul_34_8_n_112), .CI
       (mul_34_8_n_138), .CO (mul_34_8_n_175), .S (mul_34_8_n_176));
  ADDFX1 mul_34_8_g2270(.A (mul_34_8_n_135), .B (mul_34_8_n_130), .CI
       (mul_34_8_n_154), .CO (mul_34_8_n_173), .S (mul_34_8_n_174));
  ADDFX1 mul_34_8_g2271(.A (mul_34_8_n_144), .B (mul_34_8_n_149), .CI
       (mul_34_8_n_120), .CO (mul_34_8_n_171), .S (mul_34_8_n_172));
  NAND2BX1 mul_34_8_g2272(.AN (mul_34_8_n_146), .B (mul_34_8_n_167), .Y
       (mul_34_8_n_170));
  NOR2X1 mul_34_8_g2273(.A (mul_34_8_n_155), .B (mul_34_8_n_165), .Y
       (mul_34_8_n_169));
  NAND2X1 mul_34_8_g2274(.A (mul_34_8_n_155), .B (mul_34_8_n_165), .Y
       (mul_34_8_n_168));
  ADDFX1 mul_34_8_g2275(.A (mul_34_8_n_147), .B (mul_34_8_n_133), .CI
       (mul_34_8_n_117), .CO (mul_34_8_n_167), .S (out1[3]));
  ADDFX1 mul_34_8_g2276(.A (mul_34_8_n_152), .B (mul_34_8_n_82), .CI
       (mul_34_8_n_131), .CO (mul_34_8_n_164), .S (mul_34_8_n_165));
  OAI21X1 mul_34_8_g2277(.A0 (mul_34_8_n_145), .A1 (mul_34_8_n_159),
       .B0 (mul_34_8_n_157), .Y (mul_34_8_n_163));
  NAND2BX1 mul_34_8_g2278(.AN (mul_34_8_n_159), .B (mul_34_8_n_157), .Y
       (mul_34_8_n_162));
  ADDFX1 mul_34_8_g2279(.A (mul_34_8_n_137), .B (mul_34_8_n_105), .CI
       (mul_34_8_n_99), .CO (mul_34_8_n_160), .S (mul_34_8_n_161));
  NOR2X1 mul_34_8_g2280(.A (mul_34_8_n_139), .B (mul_34_8_n_156), .Y
       (mul_34_8_n_159));
  NAND2BX1 mul_34_8_g2281(.AN (mul_34_8_n_146), .B (mul_34_8_n_145), .Y
       (mul_34_8_n_158));
  NAND2X1 mul_34_8_g2282(.A (mul_34_8_n_139), .B (mul_34_8_n_156), .Y
       (mul_34_8_n_157));
  ADDFX1 mul_34_8_g2283(.A (mul_34_8_n_132), .B (mul_34_8_n_86), .CI
       (mul_34_8_n_84), .CO (mul_34_8_n_155), .S (mul_34_8_n_156));
  ADDFX1 mul_34_8_g2284(.A (mul_34_8_n_127), .B (mul_34_8_n_94), .CI
       (mul_34_8_n_106), .CO (mul_34_8_n_153), .S (mul_34_8_n_154));
  ADDFX1 mul_34_8_g2285(.A (mul_34_8_n_89), .B (mul_34_8_n_113), .CI
       (mul_34_8_n_79), .CO (mul_34_8_n_151), .S (mul_34_8_n_152));
  ADDFX1 mul_34_8_g2286(.A (mul_34_8_n_129), .B (mul_34_8_n_85), .CI
       (mul_34_8_n_101), .CO (mul_34_8_n_149), .S (mul_34_8_n_150));
  ADDFX1 mul_34_8_g2287(.A (mul_34_8_n_124), .B (mul_34_8_n_73), .CI
       (mul_34_8_n_119), .CO (mul_34_8_n_147), .S (out1[2]));
  NOR2X1 mul_34_8_g2288(.A (mul_34_8_n_134), .B (mul_34_8_n_140), .Y
       (mul_34_8_n_146));
  NAND2X1 mul_34_8_g2289(.A (mul_34_8_n_134), .B (mul_34_8_n_140), .Y
       (mul_34_8_n_145));
  ADDFX1 mul_34_8_g2290(.A (mul_34_8_n_111), .B (mul_34_8_n_93), .CI
       (mul_34_8_n_91), .CO (mul_34_8_n_143), .S (mul_34_8_n_144));
  ADDFX1 mul_34_8_g2291(.A (mul_34_8_n_97), .B (mul_34_8_n_104), .CI
       (mul_34_8_n_98), .CO (mul_34_8_n_141), .S (mul_34_8_n_142));
  ADDFX1 mul_34_8_g2292(.A (mul_34_8_n_115), .B (mul_34_8_n_72), .CI
       (mul_34_8_n_87), .CO (mul_34_8_n_139), .S (mul_34_8_n_140));
  ADDFX1 mul_34_8_g2293(.A (mul_34_8_n_95), .B (mul_34_8_n_92), .CI
       (mul_34_8_n_103), .CO (mul_34_8_n_137), .S (mul_34_8_n_138));
  ADDFX1 mul_34_8_g2294(.A (mul_34_8_n_96), .B (mul_34_8_n_83), .CI
       (mul_34_8_n_102), .CO (mul_34_8_n_135), .S (mul_34_8_n_136));
  ADDHX1 mul_34_8_g2295(.A (mul_34_8_n_110), .B (mul_34_8_n_90), .CO
       (mul_34_8_n_134), .S (mul_34_8_n_133));
  ADDHX1 mul_34_8_g2296(.A (mul_34_8_n_107), .B (mul_34_8_n_116), .CO
       (mul_34_8_n_131), .S (mul_34_8_n_132));
  ADDHX1 mul_34_8_g2297(.A (mul_34_8_n_114), .B (mul_34_8_n_88), .CO
       (mul_34_8_n_129), .S (mul_34_8_n_130));
  ADDHX1 mul_34_8_g2298(.A (mul_34_8_n_108), .B (mul_34_8_n_109), .CO
       (mul_34_8_n_127), .S (mul_34_8_n_128));
  AOI21X1 mul_34_8_g2299(.A0 (mul_34_8_n_63), .A1 (mul_34_8_n_122), .B0
       (mul_34_8_n_124), .Y (out1[1]));
  XNOR2X1 mul_34_8_g2300(.A (mul_34_8_n_118), .B (mul_34_8_n_121), .Y
       (mul_34_8_n_125));
  NOR2X1 mul_34_8_g2301(.A (mul_34_8_n_63), .B (mul_34_8_n_122), .Y
       (mul_34_8_n_124));
  OAI21XL mul_34_8_g2302(.A0 (in2[1]), .A1 (mul_34_8_n_100), .B0
       (mul_34_8_n_120), .Y (mul_34_8_n_123));
  OAI22X1 mul_34_8_g2303(.A0 (mul_34_8_n_59), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_3), .B1 (mul_34_8_n_54), .Y (mul_34_8_n_119));
  OAI2BB1X1 mul_34_8_g2304(.A0N (in2[7]), .A1N (mul_34_8_n_77), .B0
       (mul_34_8_n_75), .Y (mul_34_8_n_118));
  OAI22X1 mul_34_8_g2305(.A0 (mul_34_8_n_54), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_3), .B1 (mul_34_8_n_55), .Y (mul_34_8_n_117));
  AOI22X1 mul_34_8_g2306(.A0 (mul_34_8_n_21), .A1 (mul_34_8_n_80), .B0
       (in2[0]), .B1 (mul_34_8_n_58), .Y (mul_34_8_n_122));
  OAI22X1 mul_34_8_g2307(.A0 (mul_34_8_n_56), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_3), .B1 (mul_34_8_n_53), .Y (mul_34_8_n_116));
  OAI22X1 mul_34_8_g2308(.A0 (mul_34_8_n_55), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_3), .B1 (mul_34_8_n_56), .Y (mul_34_8_n_115));
  OAI22X1 mul_34_8_g2309(.A0 (mul_34_8_n_57), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_1), .B1 (mul_34_8_n_3), .Y (mul_34_8_n_114));
  AOI21X1 mul_34_8_g2310(.A0 (mul_34_8_n_30), .A1 (mul_34_8_n_77), .B0
       (mul_34_8_n_76), .Y (mul_34_8_n_121));
  OAI22X1 mul_34_8_g2311(.A0 (mul_34_8_n_53), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_3), .B1 (mul_34_8_n_60), .Y (mul_34_8_n_113));
  NAND2X1 mul_34_8_g2312(.A (in2[1]), .B (mul_34_8_n_100), .Y
       (mul_34_8_n_120));
  INVX1 mul_34_8_g2313(.A (mul_34_8_n_111), .Y (mul_34_8_n_112));
  AOI221X1 mul_34_8_g2314(.A0 (in1[0]), .A1 (in2[1]), .B0 (in2[2]), .B1
       (mul_34_8_n_14), .C0 (mul_34_8_n_6), .Y (mul_34_8_n_110));
  OAI22X1 mul_34_8_g2315(.A0 (mul_34_8_n_60), .A1 (mul_34_8_n_81), .B0
       (mul_34_8_n_3), .B1 (mul_34_8_n_57), .Y (mul_34_8_n_109));
  AOI221X1 mul_34_8_g2316(.A0 (in2[6]), .A1 (in2[5]), .B0 (in1[0]), .B1
       (mul_34_8_n_0), .C0 (mul_34_8_n_8), .Y (mul_34_8_n_108));
  AOI221X1 mul_34_8_g2317(.A0 (in1[0]), .A1 (in2[3]), .B0 (in2[4]), .B1
       (mul_34_8_n_15), .C0 (mul_34_8_n_7), .Y (mul_34_8_n_107));
  OAI22X1 mul_34_8_g2318(.A0 (mul_34_8_n_38), .A1 (mul_34_8_n_78), .B0
       (mul_34_8_n_29), .B1 (mul_34_8_n_22), .Y (mul_34_8_n_106));
  OAI22X1 mul_34_8_g2319(.A0 (mul_34_8_n_31), .A1 (mul_34_8_n_78), .B0
       (mul_34_8_n_34), .B1 (mul_34_8_n_22), .Y (mul_34_8_n_105));
  AO22XL mul_34_8_g2320(.A0 (mul_34_8_n_35), .A1 (mul_34_8_n_77), .B0
       (mul_34_8_n_30), .B1 (mul_34_8_n_74), .Y (mul_34_8_n_104));
  OAI22X1 mul_34_8_g2321(.A0 (mul_34_8_n_37), .A1 (mul_34_8_n_78), .B0
       (mul_34_8_n_31), .B1 (mul_34_8_n_22), .Y (mul_34_8_n_103));
  OAI22X1 mul_34_8_g2322(.A0 (mul_34_8_n_19), .A1 (mul_34_8_n_78), .B0
       (mul_34_8_n_38), .B1 (mul_34_8_n_22), .Y (mul_34_8_n_102));
  OAI22X1 mul_34_8_g2323(.A0 (mul_34_8_n_29), .A1 (mul_34_8_n_78), .B0
       (mul_34_8_n_33), .B1 (mul_34_8_n_22), .Y (mul_34_8_n_101));
  AOI22X1 mul_34_8_g2324(.A0 (mul_34_8_n_32), .A1 (mul_34_8_n_77), .B0
       (mul_34_8_n_36), .B1 (mul_34_8_n_74), .Y (mul_34_8_n_111));
  INVX1 mul_34_8_g2325(.A (mul_34_8_n_98), .Y (mul_34_8_n_99));
  AOI22X1 mul_34_8_g2326(.A0 (mul_34_8_n_25), .A1 (mul_34_8_n_68), .B0
       (mul_34_8_n_50), .B1 (mul_34_8_n_45), .Y (mul_34_8_n_100));
  AOI21X1 mul_34_8_g2327(.A0 (in2[5]), .A1 (mul_34_8_n_68), .B0
       (mul_34_8_n_67), .Y (mul_34_8_n_97));
  OAI22X1 mul_34_8_g2328(.A0 (mul_34_8_n_39), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_23), .B1 (mul_34_8_n_46), .Y (mul_34_8_n_96));
  AOI21X1 mul_34_8_g2329(.A0 (in2[3]), .A1 (mul_34_8_n_70), .B0
       (mul_34_8_n_64), .Y (mul_34_8_n_95));
  OAI22X1 mul_34_8_g2330(.A0 (mul_34_8_n_23), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_24), .B1 (mul_34_8_n_46), .Y (mul_34_8_n_94));
  OAI22X1 mul_34_8_g2331(.A0 (mul_34_8_n_49), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_48), .B1 (mul_34_8_n_46), .Y (mul_34_8_n_93));
  OAI22X1 mul_34_8_g2332(.A0 (mul_34_8_n_48), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_61), .B1 (mul_34_8_n_46), .Y (mul_34_8_n_92));
  OAI21X1 mul_34_8_g2333(.A0 (mul_34_8_n_62), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_65), .Y (mul_34_8_n_91));
  OAI21X1 mul_34_8_g2334(.A0 (mul_34_8_n_61), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_66), .Y (mul_34_8_n_98));
  OAI22X1 mul_34_8_g2335(.A0 (mul_34_8_n_18), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_27), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_90));
  OAI22X1 mul_34_8_g2336(.A0 (mul_34_8_n_28), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_39), .B1 (mul_34_8_n_46), .Y (mul_34_8_n_89));
  OAI22X1 mul_34_8_g2337(.A0 (mul_34_8_n_51), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_52), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_88));
  OAI22X1 mul_34_8_g2338(.A0 (mul_34_8_n_27), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_26), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_87));
  OAI22X1 mul_34_8_g2339(.A0 (mul_34_8_n_26), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_40), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_86));
  OAI22X1 mul_34_8_g2340(.A0 (mul_34_8_n_52), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_62), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_85));
  OAI22X1 mul_34_8_g2341(.A0 (mul_34_8_n_17), .A1 (mul_34_8_n_69), .B0
       (mul_34_8_n_28), .B1 (mul_34_8_n_46), .Y (mul_34_8_n_84));
  OAI22X1 mul_34_8_g2342(.A0 (mul_34_8_n_47), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_51), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_83));
  OAI22X1 mul_34_8_g2343(.A0 (mul_34_8_n_40), .A1 (mul_34_8_n_71), .B0
       (mul_34_8_n_47), .B1 (mul_34_8_n_44), .Y (mul_34_8_n_82));
  INVX1 mul_34_8_g2344(.A (mul_34_8_n_81), .Y (mul_34_8_n_80));
  NAND2X1 mul_34_8_g2345(.A (mul_34_8_n_3), .B (mul_34_8_n_20), .Y
       (mul_34_8_n_81));
  NOR2X1 mul_34_8_g2346(.A (mul_34_8_n_2), .B (mul_34_8_n_22), .Y
       (mul_34_8_n_79));
  INVX1 mul_34_8_g2347(.A (mul_34_8_n_78), .Y (mul_34_8_n_77));
  NAND2X1 mul_34_8_g2348(.A (mul_34_8_n_41), .B (mul_34_8_n_22), .Y
       (mul_34_8_n_78));
  INVX1 mul_34_8_g2349(.A (mul_34_8_n_75), .Y (mul_34_8_n_76));
  NAND2X1 mul_34_8_g2350(.A (in2[7]), .B (mul_34_8_n_74), .Y
       (mul_34_8_n_75));
  INVX1 mul_34_8_g2351(.A (mul_34_8_n_22), .Y (mul_34_8_n_74));
  NOR2X1 mul_34_8_g2352(.A (mul_34_8_n_2), .B (mul_34_8_n_44), .Y
       (mul_34_8_n_73));
  NOR2X1 mul_34_8_g2353(.A (mul_34_8_n_2), .B (mul_34_8_n_46), .Y
       (mul_34_8_n_72));
  INVX1 mul_34_8_g2354(.A (mul_34_8_n_71), .Y (mul_34_8_n_70));
  NAND2X1 mul_34_8_g2355(.A (mul_34_8_n_43), .B (mul_34_8_n_44), .Y
       (mul_34_8_n_71));
  INVX1 mul_34_8_g2356(.A (mul_34_8_n_69), .Y (mul_34_8_n_68));
  NAND2X1 mul_34_8_g2357(.A (mul_34_8_n_42), .B (mul_34_8_n_46), .Y
       (mul_34_8_n_69));
  INVX1 mul_34_8_g2358(.A (mul_34_8_n_66), .Y (mul_34_8_n_67));
  NAND2X1 mul_34_8_g2359(.A (in2[5]), .B (mul_34_8_n_45), .Y
       (mul_34_8_n_66));
  INVX1 mul_34_8_g2360(.A (mul_34_8_n_64), .Y (mul_34_8_n_65));
  NOR2X1 mul_34_8_g2361(.A (mul_34_8_n_6), .B (mul_34_8_n_44), .Y
       (mul_34_8_n_64));
  INVX1 mul_34_8_g2362(.A (mul_34_8_n_58), .Y (mul_34_8_n_59));
  INVX1 mul_34_8_g2363(.A (mul_34_8_n_49), .Y (mul_34_8_n_50));
  INVX1 mul_34_8_g2364(.A (mul_34_8_n_46), .Y (mul_34_8_n_45));
  MXI2XL mul_34_8_g2365(.A (mul_34_8_n_6), .B (in2[3]), .S0 (in2[2]),
       .Y (mul_34_8_n_43));
  MXI2XL mul_34_8_g2366(.A (mul_34_8_n_7), .B (in2[5]), .S0 (in2[4]),
       .Y (mul_34_8_n_42));
  MXI2XL mul_34_8_g2367(.A (mul_34_8_n_8), .B (in2[7]), .S0 (in2[6]),
       .Y (mul_34_8_n_41));
  OR2XL mul_34_8_g2368(.A (mul_34_8_n_1), .B (out1[0]), .Y
       (mul_34_8_n_63));
  AOI22X1 mul_34_8_g2369(.A0 (in1[7]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_12), .Y (mul_34_8_n_62));
  AOI22X1 mul_34_8_g2370(.A0 (in1[7]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_12), .Y (mul_34_8_n_61));
  AOI22X1 mul_34_8_g2371(.A0 (in1[6]), .A1 (mul_34_8_n_1), .B0
       (in2[1]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_60));
  OAI22X1 mul_34_8_g2372(.A0 (mul_34_8_n_5), .A1 (in2[1]), .B0
       (mul_34_8_n_1), .B1 (in1[1]), .Y (mul_34_8_n_58));
  AOI22X1 mul_34_8_g2373(.A0 (in1[7]), .A1 (mul_34_8_n_1), .B0
       (in2[1]), .B1 (mul_34_8_n_12), .Y (mul_34_8_n_57));
  AOI22X1 mul_34_8_g2374(.A0 (in1[4]), .A1 (mul_34_8_n_1), .B0
       (in2[1]), .B1 (mul_34_8_n_4), .Y (mul_34_8_n_56));
  AOI22X1 mul_34_8_g2375(.A0 (in1[3]), .A1 (mul_34_8_n_1), .B0
       (in2[1]), .B1 (mul_34_8_n_13), .Y (mul_34_8_n_55));
  AOI22X1 mul_34_8_g2376(.A0 (in1[2]), .A1 (mul_34_8_n_1), .B0
       (in2[1]), .B1 (mul_34_8_n_9), .Y (mul_34_8_n_54));
  AOI22X1 mul_34_8_g2377(.A0 (in1[5]), .A1 (mul_34_8_n_1), .B0
       (in2[1]), .B1 (mul_34_8_n_10), .Y (mul_34_8_n_53));
  AOI22X1 mul_34_8_g2378(.A0 (in1[6]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_52));
  AOI22X1 mul_34_8_g2379(.A0 (in1[5]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_10), .Y (mul_34_8_n_51));
  AOI22X1 mul_34_8_g2380(.A0 (in1[5]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_10), .Y (mul_34_8_n_49));
  AOI22X1 mul_34_8_g2381(.A0 (in1[6]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_48));
  AOI22X1 mul_34_8_g2382(.A0 (in1[4]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_4), .Y (mul_34_8_n_47));
  MX2X1 mul_34_8_g2383(.A (mul_34_8_n_6), .B (in2[3]), .S0 (in2[4]), .Y
       (mul_34_8_n_46));
  MX2X1 mul_34_8_g2384(.A (mul_34_8_n_1), .B (in2[1]), .S0 (in2[2]), .Y
       (mul_34_8_n_44));
  INVX1 mul_34_8_g2385(.A (mul_34_8_n_36), .Y (mul_34_8_n_37));
  INVXL mul_34_8_g2386(.A (mul_34_8_n_34), .Y (mul_34_8_n_35));
  INVX1 mul_34_8_g2387(.A (mul_34_8_n_32), .Y (mul_34_8_n_33));
  INVX1 mul_34_8_g2388(.A (mul_34_8_n_24), .Y (mul_34_8_n_25));
  OAI22X1 mul_34_8_g2389(.A0 (mul_34_8_n_2), .A1 (in2[1]), .B0
       (mul_34_8_n_1), .B1 (in1[0]), .Y (mul_34_8_n_21));
  OAI22X1 mul_34_8_g2390(.A0 (mul_34_8_n_1), .A1 (in2[0]), .B0
       (mul_34_8_n_3), .B1 (in2[1]), .Y (mul_34_8_n_20));
  AOI22X1 mul_34_8_g2391(.A0 (in1[0]), .A1 (mul_34_8_n_8), .B0
       (in2[7]), .B1 (mul_34_8_n_2), .Y (mul_34_8_n_19));
  AOI22X1 mul_34_8_g2392(.A0 (in1[0]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_2), .Y (mul_34_8_n_18));
  AOI22X1 mul_34_8_g2393(.A0 (in1[0]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_2), .Y (mul_34_8_n_17));
  AOI22X1 mul_34_8_g2394(.A0 (in1[3]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_13), .Y (mul_34_8_n_40));
  AOI22X1 mul_34_8_g2395(.A0 (in1[2]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_9), .Y (mul_34_8_n_39));
  AOI22X1 mul_34_8_g2396(.A0 (in1[1]), .A1 (mul_34_8_n_8), .B0
       (in2[7]), .B1 (mul_34_8_n_5), .Y (mul_34_8_n_38));
  OAI22X1 mul_34_8_g2397(.A0 (mul_34_8_n_4), .A1 (in2[7]), .B0
       (mul_34_8_n_8), .B1 (in1[4]), .Y (mul_34_8_n_36));
  AOI22X1 mul_34_8_g2398(.A0 (in1[6]), .A1 (mul_34_8_n_8), .B0
       (in2[7]), .B1 (mul_34_8_n_11), .Y (mul_34_8_n_34));
  OAI22X1 mul_34_8_g2399(.A0 (mul_34_8_n_13), .A1 (in2[7]), .B0
       (mul_34_8_n_8), .B1 (in1[3]), .Y (mul_34_8_n_32));
  AOI22X1 mul_34_8_g2400(.A0 (in1[5]), .A1 (mul_34_8_n_8), .B0
       (in2[7]), .B1 (mul_34_8_n_10), .Y (mul_34_8_n_31));
  OAI22X1 mul_34_8_g2401(.A0 (mul_34_8_n_12), .A1 (in2[7]), .B0
       (mul_34_8_n_8), .B1 (in1[7]), .Y (mul_34_8_n_30));
  AOI22X1 mul_34_8_g2402(.A0 (in1[2]), .A1 (mul_34_8_n_8), .B0
       (in2[7]), .B1 (mul_34_8_n_9), .Y (mul_34_8_n_29));
  AOI22X1 mul_34_8_g2403(.A0 (in1[1]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_5), .Y (mul_34_8_n_28));
  AOI22X1 mul_34_8_g2404(.A0 (in1[1]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_5), .Y (mul_34_8_n_27));
  AOI22X1 mul_34_8_g2405(.A0 (in1[2]), .A1 (mul_34_8_n_6), .B0
       (in2[3]), .B1 (mul_34_8_n_9), .Y (mul_34_8_n_26));
  AOI22X1 mul_34_8_g2406(.A0 (in1[4]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_4), .Y (mul_34_8_n_24));
  AOI22X1 mul_34_8_g2407(.A0 (in1[3]), .A1 (mul_34_8_n_7), .B0
       (in2[5]), .B1 (mul_34_8_n_13), .Y (mul_34_8_n_23));
  MX2X1 mul_34_8_g2408(.A (mul_34_8_n_7), .B (in2[5]), .S0 (in2[6]), .Y
       (mul_34_8_n_22));
  NOR2X1 mul_34_8_g2410(.A (mul_34_8_n_2), .B (mul_34_8_n_3), .Y
       (out1[0]));
  NAND2X1 mul_34_8_g2411(.A (mul_34_8_n_2), .B (mul_34_8_n_6), .Y
       (mul_34_8_n_15));
  NAND2X1 mul_34_8_g2412(.A (mul_34_8_n_2), .B (mul_34_8_n_1), .Y
       (mul_34_8_n_14));
  INVX1 mul_34_8_g2413(.A (in1[3]), .Y (mul_34_8_n_13));
  INVX1 mul_34_8_g2414(.A (in1[7]), .Y (mul_34_8_n_12));
  INVX1 mul_34_8_g2415(.A (in1[6]), .Y (mul_34_8_n_11));
  INVX1 mul_34_8_g2416(.A (in1[5]), .Y (mul_34_8_n_10));
  INVX1 mul_34_8_g2417(.A (in1[2]), .Y (mul_34_8_n_9));
  INVX1 mul_34_8_g2418(.A (in2[7]), .Y (mul_34_8_n_8));
  INVX1 mul_34_8_g2419(.A (in2[5]), .Y (mul_34_8_n_7));
  INVX1 mul_34_8_g2420(.A (in2[3]), .Y (mul_34_8_n_6));
  INVX1 mul_34_8_g2422(.A (in1[1]), .Y (mul_34_8_n_5));
  INVX1 mul_34_8_g2423(.A (in1[4]), .Y (mul_34_8_n_4));
  INVX1 mul_34_8_g2424(.A (in2[0]), .Y (mul_34_8_n_3));
  INVX1 mul_34_8_g2425(.A (in1[0]), .Y (mul_34_8_n_2));
  INVX1 mul_34_8_g2426(.A (in2[1]), .Y (mul_34_8_n_1));
  NAND2BX1 mul_34_8_g2(.AN (in2[6]), .B (mul_34_8_n_7), .Y
       (mul_34_8_n_0));
endmodule


