`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: Nov 16 2019 23:12:16 CST (Nov 16 2019 15:12:16 UTC)

module SobelFilter_Add_2Ux2U_2U_1(in2, in1, out1);
  input [1:0] in2, in1;
  output [1:0] out1;
  wire [1:0] in2, in1;
  wire [1:0] out1;
  wire add_35_2_n_0, add_35_2_n_1, add_35_2_n_2, add_35_2_n_3,
       add_35_2_n_4, add_35_2_n_5, add_35_2_n_7, add_35_2_n_8;
  MXI2X1 add_35_2_g25(.A (add_35_2_n_8), .B (add_35_2_n_3), .S0
       (add_35_2_n_7), .Y (out1[1]));
  INVX1 add_35_2_g26(.A (add_35_2_n_3), .Y (add_35_2_n_8));
  NAND2X1 add_35_2_g27(.A (add_35_2_n_4), .B (add_35_2_n_5), .Y
       (add_35_2_n_7));
  MXI2XL add_35_2_g28(.A (add_35_2_n_1), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NAND2X4 add_35_2_g29(.A (add_35_2_n_2), .B (add_35_2_n_0), .Y
       (add_35_2_n_5));
  NAND2X1 add_35_2_g30(.A (in2[1]), .B (in1[1]), .Y (add_35_2_n_4));
  NAND2X1 add_35_2_g31(.A (in2[0]), .B (in1[0]), .Y (add_35_2_n_3));
  CLKINVX12 add_35_2_g32(.A (in2[1]), .Y (add_35_2_n_2));
  INVX1 add_35_2_g33(.A (in2[0]), .Y (add_35_2_n_1));
  CLKINVX20 add_35_2_g34(.A (in1[1]), .Y (add_35_2_n_0));
endmodule


